package ru.rdtex.mvd.weapon.model.vo;

import oracle.jbo.server.ViewObjectImpl;

import ru.rdtex.mvd.weapon.model.am.AppModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 09 11:34:13 MSD 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CountryViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CountryViewImpl() {
    }

    /**
     * Returns the variable value for ftitle.
     * @return variable value for ftitle
     */
    public String getftitle() {
        return (String)ensureVariableManager().getVariableValue("ftitle");
    }

    /**
     * Sets <code>value</code> for variable ftitle.
     * @param value value to bind as ftitle
     */
    public void setftitle(String value) {
        ensureVariableManager().setVariableValue("ftitle", value);
    }
}
