package ru.rdtex.mvd.weapon.model.vo;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 10 14:58:45 MSD 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DocDocumentsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DocDocumentsViewImpl() {
    }

    /**
     * Returns the variable value for personId.
     * @return variable value for personId
     */
    public Number getpersonId() {
        return (Number)ensureVariableManager().getVariableValue("personId");
    }

    /**
     * Sets <code>value</code> for variable personId.
     * @param value value to bind as personId
     */
    public void setpersonId(Number value) {
        ensureVariableManager().setVariableValue("personId", value);
    }
}
