package ru.rdtex.mvd.weapon.model.vo;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;

import ru.rdtex.mvd.weapon.global.JSFUtils;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 10 11:41:38 MSD 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DocPermissionsViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        BlnkId {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getBlnkId();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setBlnkId((Number)value);
            }
        }
        ,
        CountryCodeIn {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getCountryCodeIn();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setCountryCodeIn((Number)value);
            }
        }
        ,
        CountryCodeOut {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getCountryCodeOut();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setCountryCodeOut((Number)value);
            }
        }
        ,
        DdcId {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getDdcId();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setDdcId((Number)value);
            }
        }
        ,
        EndDate {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getEndDate();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setEndDate((Date)value);
            }
        }
        ,
        Reason {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getReason();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setReason((String)value);
            }
        }
        ,
        Duplicate {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getDuplicate();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setDuplicate((Number)value);
            }
        }
        ,
        DuplicatePers {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getDuplicatePers();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setDuplicatePers((Number)value);
            }
        }
        ,
        SaleDate {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getSaleDate();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setSaleDate((Date)value);
            }
        }
        ,
        Shop {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getShop();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setShop((String)value);
            }
        }
        ,
        TypelicIdPermission {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getTypelicIdPermission();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setTypelicIdPermission((Number)value);
            }
        }
        ,
        UpdatedFlag {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getUpdatedFlag();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setUpdatedFlag((Number)value);
            }
        }
        ,
        EndDateDirect {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getEndDateDirect();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setEndDateDirect((Date)value);
            }
        }
        ,
        RemoveDate {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getRemoveDate();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setRemoveDate((Date)value);
            }
        }
        ,
        ImportDate {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getImportDate();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setImportDate((Date)value);
            }
        }
        ,
        ObjId {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getObjId();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setObjId((Number)value);
            }
        }
        ,
        Path {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getPath();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setPath((String)value);
            }
        }
        ,
        CustOut {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getCustOut();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setCustOut((Number)value);
            }
        }
        ,
        Transport {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getTransport();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setTransport((String)value);
            }
        }
        ,
        CustIn {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getCustIn();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setCustIn((Number)value);
            }
        }
        ,
        Department {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getDepartment();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setDepartment((String)value);
            }
        }
        ,
        HeadSign {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getHeadSign();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setHeadSign((String)value);
            }
        }
        ,
        EmpSign {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getEmpSign();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setEmpSign((String)value);
            }
        }
        ,
        StatusDate {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getStatusDate();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setStatusDate((Date)value);
            }
        }
        ,
        ResponPerson {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getResponPerson();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setResponPerson((String)value);
            }
        }
        ,
        LicstatCode {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getLicstatCode();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setLicstatCode((Number)value);
            }
        }
        ,
        Id {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getId();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        State {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getState();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setState((Number)value);
            }
        }
        ,
        Inserted {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getInserted();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setInserted((Date)value);
            }
        }
        ,
        InsertedBy {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getInsertedBy();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setInsertedBy((Number)value);
            }
        }
        ,
        Updated {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getUpdated();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setUpdated((Date)value);
            }
        }
        ,
        UpdatedBy {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getUpdatedBy();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setUpdatedBy((Number)value);
            }
        }
        ,
        PaySum {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getPaySum();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setPaySum((Number)value);
            }
        }
        ,
        EpFId {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getEpFId();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setEpFId((Number)value);
            }
        }
        ,
        ObjLow {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getObjLow();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setObjLow((String)value);
            }
        }
        ,
        Wh {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getWh();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setWh((String)value);
            }
        }
        ,
        EadrId {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getEadrId();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setEadrId((Number)value);
            }
        }
        ,
        RegionCode {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getRegionCode();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setRegionCode((Number)value);
            }
        }
        ,
        Ovd {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getOvd();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setOvd((String)value);
            }
        }
        ,
        RegionDept {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getRegionDept();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setRegionDept((String)value);
            }
        }
        ,
        MunDistrict {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getMunDistrict();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setMunDistrict((String)value);
            }
        }
        ,
        Town {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getTown();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setTown((String)value);
            }
        }
        ,
        PayDate {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getPayDate();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setPayDate((Date)value);
            }
        }
        ,
        DetectiveNumb {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getDetectiveNumb();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setDetectiveNumb((String)value);
            }
        }
        ,
        HashValue {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getHashValue();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setHashValue((Number)value);
            }
        }
        ,
        PsgCancelReason {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getPsgCancelReason();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setPsgCancelReason((String)value);
            }
        }
        ,
        PsgLossDescr {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getPsgLossDescr();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setPsgLossDescr((String)value);
            }
        }
        ,
        PersonType {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getPersonType();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setPersonType((String)value);
            }
        }
        ,
        TypeBlankList {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getTypeBlankList();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setTypeBlankList((String)value);
            }
        }
        ,
        TypelicIdLicense {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getTypelicIdLicense();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setTypelicIdLicense((Number)value);
            }
        }
        ,
        TypeLicenceView1 {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getTypeLicenceView1();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StatusLicenceView1 {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getStatusLicenceView1();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AcsUsersView1 {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getAcsUsersView1();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        HeadsView1 {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getHeadsView1();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TypeLicenceView2 {
            public Object get(DocPermissionsViewRowImpl obj) {
                return obj.getTypeLicenceView2();
            }

            public void put(DocPermissionsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(DocPermissionsViewRowImpl object);

        public abstract void put(DocPermissionsViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BLNKID = AttributesEnum.BlnkId.index();
    public static final int COUNTRYCODEIN = AttributesEnum.CountryCodeIn.index();
    public static final int COUNTRYCODEOUT = AttributesEnum.CountryCodeOut.index();
    public static final int DDCID = AttributesEnum.DdcId.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int REASON = AttributesEnum.Reason.index();
    public static final int DUPLICATE = AttributesEnum.Duplicate.index();
    public static final int DUPLICATEPERS = AttributesEnum.DuplicatePers.index();
    public static final int SALEDATE = AttributesEnum.SaleDate.index();
    public static final int SHOP = AttributesEnum.Shop.index();
    public static final int TYPELICIDPERMISSION = AttributesEnum.TypelicIdPermission.index();
    public static final int UPDATEDFLAG = AttributesEnum.UpdatedFlag.index();
    public static final int ENDDATEDIRECT = AttributesEnum.EndDateDirect.index();
    public static final int REMOVEDATE = AttributesEnum.RemoveDate.index();
    public static final int IMPORTDATE = AttributesEnum.ImportDate.index();
    public static final int OBJID = AttributesEnum.ObjId.index();
    public static final int PATH = AttributesEnum.Path.index();
    public static final int CUSTOUT = AttributesEnum.CustOut.index();
    public static final int TRANSPORT = AttributesEnum.Transport.index();
    public static final int CUSTIN = AttributesEnum.CustIn.index();
    public static final int DEPARTMENT = AttributesEnum.Department.index();
    public static final int HEADSIGN = AttributesEnum.HeadSign.index();
    public static final int EMPSIGN = AttributesEnum.EmpSign.index();
    public static final int STATUSDATE = AttributesEnum.StatusDate.index();
    public static final int RESPONPERSON = AttributesEnum.ResponPerson.index();
    public static final int LICSTATCODE = AttributesEnum.LicstatCode.index();
    public static final int ID = AttributesEnum.Id.index();
    public static final int STATE = AttributesEnum.State.index();
    public static final int INSERTED = AttributesEnum.Inserted.index();
    public static final int INSERTEDBY = AttributesEnum.InsertedBy.index();
    public static final int UPDATED = AttributesEnum.Updated.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int PAYSUM = AttributesEnum.PaySum.index();
    public static final int EPFID = AttributesEnum.EpFId.index();
    public static final int OBJLOW = AttributesEnum.ObjLow.index();
    public static final int WH = AttributesEnum.Wh.index();
    public static final int EADRID = AttributesEnum.EadrId.index();
    public static final int REGIONCODE = AttributesEnum.RegionCode.index();
    public static final int OVD = AttributesEnum.Ovd.index();
    public static final int REGIONDEPT = AttributesEnum.RegionDept.index();
    public static final int MUNDISTRICT = AttributesEnum.MunDistrict.index();
    public static final int TOWN = AttributesEnum.Town.index();
    public static final int PAYDATE = AttributesEnum.PayDate.index();
    public static final int DETECTIVENUMB = AttributesEnum.DetectiveNumb.index();
    public static final int HASHVALUE = AttributesEnum.HashValue.index();
    public static final int PSGCANCELREASON = AttributesEnum.PsgCancelReason.index();
    public static final int PSGLOSSDESCR = AttributesEnum.PsgLossDescr.index();
    public static final int PERSONTYPE = AttributesEnum.PersonType.index();
    public static final int TYPEBLANKLIST = AttributesEnum.TypeBlankList.index();
    public static final int TYPELICIDLICENSE = AttributesEnum.TypelicIdLicense.index();
    public static final int TYPELICENCEVIEW1 = AttributesEnum.TypeLicenceView1.index();
    public static final int STATUSLICENCEVIEW1 = AttributesEnum.StatusLicenceView1.index();
    public static final int ACSUSERSVIEW1 = AttributesEnum.AcsUsersView1.index();
    public static final int HEADSVIEW1 = AttributesEnum.HeadsView1.index();
    public static final int TYPELICENCEVIEW2 = AttributesEnum.TypeLicenceView2.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DocPermissionsViewRowImpl() {
    }

    /**
     * Gets DocPermissions entity object.
     * @return the DocPermissions
     */
    public EntityImpl getDocPermissions() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for BLNK_ID using the alias name BlnkId.
     * @return the BLNK_ID
     */
    public Number getBlnkId() {
        return (Number) getAttributeInternal(BLNKID);
    }

    /**
     * Sets <code>value</code> as attribute value for BLNK_ID using the alias name BlnkId.
     * @param value value to set the BLNK_ID
     */
    public void setBlnkId(Number value) {
        setAttributeInternal(BLNKID, value);
    }

    /**
     * Gets the attribute value for COUNTRY_CODE_IN using the alias name CountryCodeIn.
     * @return the COUNTRY_CODE_IN
     */
    public Number getCountryCodeIn() {
        return (Number) getAttributeInternal(COUNTRYCODEIN);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY_CODE_IN using the alias name CountryCodeIn.
     * @param value value to set the COUNTRY_CODE_IN
     */
    public void setCountryCodeIn(Number value) {
        setAttributeInternal(COUNTRYCODEIN, value);
    }

    /**
     * Gets the attribute value for COUNTRY_CODE_OUT using the alias name CountryCodeOut.
     * @return the COUNTRY_CODE_OUT
     */
    public Number getCountryCodeOut() {
        return (Number) getAttributeInternal(COUNTRYCODEOUT);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY_CODE_OUT using the alias name CountryCodeOut.
     * @param value value to set the COUNTRY_CODE_OUT
     */
    public void setCountryCodeOut(Number value) {
        setAttributeInternal(COUNTRYCODEOUT, value);
    }

    /**
     * Gets the attribute value for DDC_ID using the alias name DdcId.
     * @return the DDC_ID
     */
    public Number getDdcId() {
        return (Number) getAttributeInternal(DDCID);
    }

    /**
     * Sets <code>value</code> as attribute value for DDC_ID using the alias name DdcId.
     * @param value value to set the DDC_ID
     */
    public void setDdcId(Number value) {
        setAttributeInternal(DDCID, value);
    }

    /**
     * Gets the attribute value for END_DATE using the alias name EndDate.
     * @return the END_DATE
     */
    public Date getEndDate() {
        return (Date) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
     * @param value value to set the END_DATE
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for REASON using the alias name Reason.
     * @return the REASON
     */
    public String getReason() {
        return (String) getAttributeInternal(REASON);
    }

    /**
     * Sets <code>value</code> as attribute value for REASON using the alias name Reason.
     * @param value value to set the REASON
     */
    public void setReason(String value) {
        setAttributeInternal(REASON, value);
    }

    /**
     * Gets the attribute value for DUPLICATE using the alias name Duplicate.
     * @return the DUPLICATE
     */
    public Number getDuplicate() {
        return (Number) getAttributeInternal(DUPLICATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DUPLICATE using the alias name Duplicate.
     * @param value value to set the DUPLICATE
     */
    public void setDuplicate(Number value) {
        setAttributeInternal(DUPLICATE, value);
    }

    /**
     * Gets the attribute value for DUPLICATE_PERS using the alias name DuplicatePers.
     * @return the DUPLICATE_PERS
     */
    public Number getDuplicatePers() {
        return (Number) getAttributeInternal(DUPLICATEPERS);
    }

    /**
     * Sets <code>value</code> as attribute value for DUPLICATE_PERS using the alias name DuplicatePers.
     * @param value value to set the DUPLICATE_PERS
     */
    public void setDuplicatePers(Number value) {
        setAttributeInternal(DUPLICATEPERS, value);
    }

    /**
     * Gets the attribute value for SALE_DATE using the alias name SaleDate.
     * @return the SALE_DATE
     */
    public Date getSaleDate() {
        return (Date) getAttributeInternal(SALEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SALE_DATE using the alias name SaleDate.
     * @param value value to set the SALE_DATE
     */
    public void setSaleDate(Date value) {
        setAttributeInternal(SALEDATE, value);
    }

    /**
     * Gets the attribute value for SHOP using the alias name Shop.
     * @return the SHOP
     */
    public String getShop() {
        return (String) getAttributeInternal(SHOP);
    }

    /**
     * Sets <code>value</code> as attribute value for SHOP using the alias name Shop.
     * @param value value to set the SHOP
     */
    public void setShop(String value) {
        setAttributeInternal(SHOP, value);
    }

    /**
     * Gets the attribute value for TYPELIC_ID using the alias name TypelicIdPermission.
     * @return the TYPELIC_ID
     */
    public Number getTypelicIdPermission() {
        return (Number) getAttributeInternal(TYPELICIDPERMISSION);
    }

    /**
     * Sets <code>value</code> as attribute value for TYPELIC_ID using the alias name TypelicIdPermission.
     * @param value value to set the TYPELIC_ID
     */
    public void setTypelicIdPermission(Number value) {
        setAttributeInternal(TYPELICIDPERMISSION, value);
    }

    /**
     * Gets the attribute value for UPDATED_FLAG using the alias name UpdatedFlag.
     * @return the UPDATED_FLAG
     */
    public Number getUpdatedFlag() {
        return (Number) getAttributeInternal(UPDATEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_FLAG using the alias name UpdatedFlag.
     * @param value value to set the UPDATED_FLAG
     */
    public void setUpdatedFlag(Number value) {
        setAttributeInternal(UPDATEDFLAG, value);
    }

    /**
     * Gets the attribute value for END_DATE_DIRECT using the alias name EndDateDirect.
     * @return the END_DATE_DIRECT
     */
    public Date getEndDateDirect() {
        return (Date) getAttributeInternal(ENDDATEDIRECT);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE_DIRECT using the alias name EndDateDirect.
     * @param value value to set the END_DATE_DIRECT
     */
    public void setEndDateDirect(Date value) {
        setAttributeInternal(ENDDATEDIRECT, value);
    }

    /**
     * Gets the attribute value for REMOVE_DATE using the alias name RemoveDate.
     * @return the REMOVE_DATE
     */
    public Date getRemoveDate() {
        return (Date) getAttributeInternal(REMOVEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REMOVE_DATE using the alias name RemoveDate.
     * @param value value to set the REMOVE_DATE
     */
    public void setRemoveDate(Date value) {
        setAttributeInternal(REMOVEDATE, value);
    }

    /**
     * Gets the attribute value for IMPORT_DATE using the alias name ImportDate.
     * @return the IMPORT_DATE
     */
    public Date getImportDate() {
        return (Date) getAttributeInternal(IMPORTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for IMPORT_DATE using the alias name ImportDate.
     * @param value value to set the IMPORT_DATE
     */
    public void setImportDate(Date value) {
        setAttributeInternal(IMPORTDATE, value);
    }

    /**
     * Gets the attribute value for OBJ_ID using the alias name ObjId.
     * @return the OBJ_ID
     */
    public Number getObjId() {
        return (Number) getAttributeInternal(OBJID);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJ_ID using the alias name ObjId.
     * @param value value to set the OBJ_ID
     */
    public void setObjId(Number value) {
        setAttributeInternal(OBJID, value);
    }

    /**
     * Gets the attribute value for PATH using the alias name Path.
     * @return the PATH
     */
    public String getPath() {
        return (String) getAttributeInternal(PATH);
    }

    /**
     * Sets <code>value</code> as attribute value for PATH using the alias name Path.
     * @param value value to set the PATH
     */
    public void setPath(String value) {
        setAttributeInternal(PATH, value);
    }

    /**
     * Gets the attribute value for CUST_OUT using the alias name CustOut.
     * @return the CUST_OUT
     */
    public Number getCustOut() {
        return (Number) getAttributeInternal(CUSTOUT);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_OUT using the alias name CustOut.
     * @param value value to set the CUST_OUT
     */
    public void setCustOut(Number value) {
        setAttributeInternal(CUSTOUT, value);
    }

    /**
     * Gets the attribute value for TRANSPORT using the alias name Transport.
     * @return the TRANSPORT
     */
    public String getTransport() {
        return (String) getAttributeInternal(TRANSPORT);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSPORT using the alias name Transport.
     * @param value value to set the TRANSPORT
     */
    public void setTransport(String value) {
        setAttributeInternal(TRANSPORT, value);
    }

    /**
     * Gets the attribute value for CUST_IN using the alias name CustIn.
     * @return the CUST_IN
     */
    public Number getCustIn() {
        return (Number) getAttributeInternal(CUSTIN);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_IN using the alias name CustIn.
     * @param value value to set the CUST_IN
     */
    public void setCustIn(Number value) {
        setAttributeInternal(CUSTIN, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT using the alias name Department.
     * @return the DEPARTMENT
     */
    public String getDepartment() {
        return (String) getAttributeInternal(DEPARTMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT using the alias name Department.
     * @param value value to set the DEPARTMENT
     */
    public void setDepartment(String value) {
        setAttributeInternal(DEPARTMENT, value);
    }

    /**
     * Gets the attribute value for HEAD_SIGN using the alias name HeadSign.
     * @return the HEAD_SIGN
     */
    public String getHeadSign() {
        return (String) getAttributeInternal(HEADSIGN);
    }

    /**
     * Sets <code>value</code> as attribute value for HEAD_SIGN using the alias name HeadSign.
     * @param value value to set the HEAD_SIGN
     */
    public void setHeadSign(String value) {
        setAttributeInternal(HEADSIGN, value);
    }

    /**
     * Gets the attribute value for EMP_SIGN using the alias name EmpSign.
     * @return the EMP_SIGN
     */
    public String getEmpSign() {
        return (String) getAttributeInternal(EMPSIGN);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_SIGN using the alias name EmpSign.
     * @param value value to set the EMP_SIGN
     */
    public void setEmpSign(String value) {
        setAttributeInternal(EMPSIGN, value);
    }

    /**
     * Gets the attribute value for STATUS_DATE using the alias name StatusDate.
     * @return the STATUS_DATE
     */
    public Date getStatusDate() {
        return (Date) getAttributeInternal(STATUSDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS_DATE using the alias name StatusDate.
     * @param value value to set the STATUS_DATE
     */
    public void setStatusDate(Date value) {
        setAttributeInternal(STATUSDATE, value);
    }

    /**
     * Gets the attribute value for RESPON_PERSON using the alias name ResponPerson.
     * @return the RESPON_PERSON
     */
    public String getResponPerson() {
        return (String) getAttributeInternal(RESPONPERSON);
    }

    /**
     * Sets <code>value</code> as attribute value for RESPON_PERSON using the alias name ResponPerson.
     * @param value value to set the RESPON_PERSON
     */
    public void setResponPerson(String value) {
        setAttributeInternal(RESPONPERSON, value);
    }

    /**
     * Gets the attribute value for LICSTAT_CODE using the alias name LicstatCode.
     * @return the LICSTAT_CODE
     */
    public Number getLicstatCode() {
        return (Number) getAttributeInternal(LICSTATCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for LICSTAT_CODE using the alias name LicstatCode.
     * @param value value to set the LICSTAT_CODE
     */
    public void setLicstatCode(Number value) {
        setAttributeInternal(LICSTATCODE, value);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for STATE using the alias name State.
     * @return the STATE
     */
    public Number getState() {
        return (Number) getAttributeInternal(STATE);
    }

    /**
     * Sets <code>value</code> as attribute value for STATE using the alias name State.
     * @param value value to set the STATE
     */
    public void setState(Number value) {
        setAttributeInternal(STATE, value);
    }

    /**
     * Gets the attribute value for INSERTED using the alias name Inserted.
     * @return the INSERTED
     */
    public Date getInserted() {
        return (Date) getAttributeInternal(INSERTED);
    }

    /**
     * Sets <code>value</code> as attribute value for INSERTED using the alias name Inserted.
     * @param value value to set the INSERTED
     */
    public void setInserted(Date value) {
        setAttributeInternal(INSERTED, value);
    }

    /**
     * Gets the attribute value for INSERTED_BY using the alias name InsertedBy.
     * @return the INSERTED_BY
     */
    public Number getInsertedBy() {
        return (Number) getAttributeInternal(INSERTEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for INSERTED_BY using the alias name InsertedBy.
     * @param value value to set the INSERTED_BY
     */
    public void setInsertedBy(Number value) {
        setAttributeInternal(INSERTEDBY, value);
    }

    /**
     * Gets the attribute value for UPDATED using the alias name Updated.
     * @return the UPDATED
     */
    public Date getUpdated() {
        return (Date) getAttributeInternal(UPDATED);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED using the alias name Updated.
     * @param value value to set the UPDATED
     */
    public void setUpdated(Date value) {
        setAttributeInternal(UPDATED, value);
    }

    /**
     * Gets the attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @return the UPDATED_BY
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @param value value to set the UPDATED_BY
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for PAY_SUM using the alias name PaySum.
     * @return the PAY_SUM
     */
    public Number getPaySum() {
        return (Number) getAttributeInternal(PAYSUM);
    }

    /**
     * Sets <code>value</code> as attribute value for PAY_SUM using the alias name PaySum.
     * @param value value to set the PAY_SUM
     */
    public void setPaySum(Number value) {
        setAttributeInternal(PAYSUM, value);
    }

    /**
     * Gets the attribute value for EP_F_ID using the alias name EpFId.
     * @return the EP_F_ID
     */
    public Number getEpFId() {
        return (Number) getAttributeInternal(EPFID);
    }

    /**
     * Sets <code>value</code> as attribute value for EP_F_ID using the alias name EpFId.
     * @param value value to set the EP_F_ID
     */
    public void setEpFId(Number value) {
        setAttributeInternal(EPFID, value);
    }

    /**
     * Gets the attribute value for OBJ_LOW using the alias name ObjLow.
     * @return the OBJ_LOW
     */
    public String getObjLow() {
        return (String) getAttributeInternal(OBJLOW);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJ_LOW using the alias name ObjLow.
     * @param value value to set the OBJ_LOW
     */
    public void setObjLow(String value) {
        setAttributeInternal(OBJLOW, value);
    }

    /**
     * Gets the attribute value for WH using the alias name Wh.
     * @return the WH
     */
    public String getWh() {
        return (String) getAttributeInternal(WH);
    }

    /**
     * Sets <code>value</code> as attribute value for WH using the alias name Wh.
     * @param value value to set the WH
     */
    public void setWh(String value) {
        setAttributeInternal(WH, value);
    }

    /**
     * Gets the attribute value for EADR_ID using the alias name EadrId.
     * @return the EADR_ID
     */
    public Number getEadrId() {
        return (Number) getAttributeInternal(EADRID);
    }

    /**
     * Sets <code>value</code> as attribute value for EADR_ID using the alias name EadrId.
     * @param value value to set the EADR_ID
     */
    public void setEadrId(Number value) {
        setAttributeInternal(EADRID, value);
    }

    /**
     * Gets the attribute value for REGION_CODE using the alias name RegionCode.
     * @return the REGION_CODE
     */
    public Number getRegionCode() {
        return (Number) getAttributeInternal(REGIONCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for REGION_CODE using the alias name RegionCode.
     * @param value value to set the REGION_CODE
     */
    public void setRegionCode(Number value) {
        setAttributeInternal(REGIONCODE, value);
    }

    /**
     * Gets the attribute value for OVD using the alias name Ovd.
     * @return the OVD
     */
    public String getOvd() {
        return (String) getAttributeInternal(OVD);
    }

    /**
     * Sets <code>value</code> as attribute value for OVD using the alias name Ovd.
     * @param value value to set the OVD
     */
    public void setOvd(String value) {
        setAttributeInternal(OVD, value);
    }

    /**
     * Gets the attribute value for REGION_DEPT using the alias name RegionDept.
     * @return the REGION_DEPT
     */
    public String getRegionDept() {
        return (String) getAttributeInternal(REGIONDEPT);
    }

    /**
     * Sets <code>value</code> as attribute value for REGION_DEPT using the alias name RegionDept.
     * @param value value to set the REGION_DEPT
     */
    public void setRegionDept(String value) {
        setAttributeInternal(REGIONDEPT, value);
    }

    /**
     * Gets the attribute value for MUN_DISTRICT using the alias name MunDistrict.
     * @return the MUN_DISTRICT
     */
    public String getMunDistrict() {
        return (String) getAttributeInternal(MUNDISTRICT);
    }

    /**
     * Sets <code>value</code> as attribute value for MUN_DISTRICT using the alias name MunDistrict.
     * @param value value to set the MUN_DISTRICT
     */
    public void setMunDistrict(String value) {
        setAttributeInternal(MUNDISTRICT, value);
    }

    /**
     * Gets the attribute value for TOWN using the alias name Town.
     * @return the TOWN
     */
    public String getTown() {
        return (String) getAttributeInternal(TOWN);
    }

    /**
     * Sets <code>value</code> as attribute value for TOWN using the alias name Town.
     * @param value value to set the TOWN
     */
    public void setTown(String value) {
        setAttributeInternal(TOWN, value);
    }

    /**
     * Gets the attribute value for PAY_DATE using the alias name PayDate.
     * @return the PAY_DATE
     */
    public Date getPayDate() {
        return (Date) getAttributeInternal(PAYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PAY_DATE using the alias name PayDate.
     * @param value value to set the PAY_DATE
     */
    public void setPayDate(Date value) {
        setAttributeInternal(PAYDATE, value);
    }

    /**
     * Gets the attribute value for DETECTIVE_NUMB using the alias name DetectiveNumb.
     * @return the DETECTIVE_NUMB
     */
    public String getDetectiveNumb() {
        return (String) getAttributeInternal(DETECTIVENUMB);
    }

    /**
     * Sets <code>value</code> as attribute value for DETECTIVE_NUMB using the alias name DetectiveNumb.
     * @param value value to set the DETECTIVE_NUMB
     */
    public void setDetectiveNumb(String value) {
        setAttributeInternal(DETECTIVENUMB, value);
    }

    /**
     * Gets the attribute value for HASH_VALUE using the alias name HashValue.
     * @return the HASH_VALUE
     */
    public Number getHashValue() {
        return (Number) getAttributeInternal(HASHVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for HASH_VALUE using the alias name HashValue.
     * @param value value to set the HASH_VALUE
     */
    public void setHashValue(Number value) {
        setAttributeInternal(HASHVALUE, value);
    }

    /**
     * Gets the attribute value for PSG_CANCEL_REASON using the alias name PsgCancelReason.
     * @return the PSG_CANCEL_REASON
     */
    public String getPsgCancelReason() {
        return (String) getAttributeInternal(PSGCANCELREASON);
    }

    /**
     * Sets <code>value</code> as attribute value for PSG_CANCEL_REASON using the alias name PsgCancelReason.
     * @param value value to set the PSG_CANCEL_REASON
     */
    public void setPsgCancelReason(String value) {
        setAttributeInternal(PSGCANCELREASON, value);
    }

    /**
     * Gets the attribute value for PSG_LOSS_DESCR using the alias name PsgLossDescr.
     * @return the PSG_LOSS_DESCR
     */
    public String getPsgLossDescr() {
        return (String) getAttributeInternal(PSGLOSSDESCR);
    }

    /**
     * Sets <code>value</code> as attribute value for PSG_LOSS_DESCR using the alias name PsgLossDescr.
     * @param value value to set the PSG_LOSS_DESCR
     */
    public void setPsgLossDescr(String value) {
        setAttributeInternal(PSGLOSSDESCR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PersonType.
     * @return the PersonType
     */
    public String getPersonType() {
        //return (String) getAttributeInternal(PERSONTYPE);
        return (String)JSFUtils.resolveExpression("#{Myses.personType}");
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PersonType.
     * @param value value to set the  PersonType
     */
    public void setPersonType(String value) {
        setAttributeInternal(PERSONTYPE, value);
    }


    /**
     * Gets the attribute value for the calculated attribute TypeBlankList.
     * @return the TypeBlankList
     */
    public String getTypeBlankList() {
        return (String) getAttributeInternal(TYPEBLANKLIST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TypeBlankList.
     * @param value value to set the  TypeBlankList
     */
    public void setTypeBlankList(String value) {
        setAttributeInternal(TYPEBLANKLIST, value);
    }

    /**
     * Gets the attribute value for TYPELIC_ID using the alias name TypelicIdLicense.
     * @return the TYPELIC_ID
     */
    public Number getTypelicIdLicense() {
        return (Number) getAttributeInternal(TYPELICIDLICENSE);
    }

    /**
     * Sets <code>value</code> as attribute value for TYPELIC_ID using the alias name TypelicIdLicense.
     * @param value value to set the TYPELIC_ID
     */
    public void setTypelicIdLicense(Number value) {
        setAttributeInternal(TYPELICIDLICENSE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TypeLicenceView1.
     */
    public RowSet getTypeLicenceView1() {
        return (RowSet)getAttributeInternal(TYPELICENCEVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StatusLicenceView1.
     */
    public RowSet getStatusLicenceView1() {
        return (RowSet)getAttributeInternal(STATUSLICENCEVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AcsUsersView1.
     */
    public RowSet getAcsUsersView1() {
        return (RowSet)getAttributeInternal(ACSUSERSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> HeadsView1.
     */
    public RowSet getHeadsView1() {
        return (RowSet)getAttributeInternal(HEADSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TypeLicenceView2.
     */
    public RowSet getTypeLicenceView2() {
        return (RowSet)getAttributeInternal(TYPELICENCEVIEW2);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
