package ru.rdtex.mvd.weapon.model.vo;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 19 17:17:20 MSD 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EntAddressesViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getId();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        State {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getState();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setState((Number)value);
            }
        }
        ,
        Inserted {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getInserted();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setInserted((Date)value);
            }
        }
        ,
        InsertedBy {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getInsertedBy();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setInsertedBy((Number)value);
            }
        }
        ,
        Updated {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getUpdated();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setUpdated((Date)value);
            }
        }
        ,
        UpdatedBy {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getUpdatedBy();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setUpdatedBy((Number)value);
            }
        }
        ,
        EpId {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getEpId();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setEpId((Number)value);
            }
        }
        ,
        RegionCode {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getRegionCode();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setRegionCode((Number)value);
            }
        }
        ,
        CountryCode {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getCountryCode();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setCountryCode((Number)value);
            }
        }
        ,
        TypeAddr {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getTypeAddr();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setTypeAddr((String)value);
            }
        }
        ,
        RegionDept {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getRegionDept();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setRegionDept((String)value);
            }
        }
        ,
        Town {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getTown();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setTown((String)value);
            }
        }
        ,
        Street {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getStreet();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setStreet((String)value);
            }
        }
        ,
        House {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getHouse();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setHouse((String)value);
            }
        }
        ,
        Corpus {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getCorpus();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setCorpus((String)value);
            }
        }
        ,
        Room {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getRoom();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setRoom((String)value);
            }
        }
        ,
        AdmDistrict {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getAdmDistrict();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setAdmDistrict((String)value);
            }
        }
        ,
        MunDistrict {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getMunDistrict();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setMunDistrict((String)value);
            }
        }
        ,
        Police {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getPolice();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setPolice((String)value);
            }
        }
        ,
        Phone {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getPhone();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setPhone((String)value);
            }
        }
        ,
        UpdatedFlag {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getUpdatedFlag();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setUpdatedFlag((Number)value);
            }
        }
        ,
        SDate {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getSDate();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setSDate((Date)value);
            }
        }
        ,
        EDate {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getEDate();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setEDate((Date)value);
            }
        }
        ,
        StrAdrs {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getStrAdrs();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setStrAdrs((String)value);
            }
        }
        ,
        Wh {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getWh();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setWh((String)value);
            }
        }
        ,
        Propiska {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getPropiska();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setPropiska((Date)value);
            }
        }
        ,
        HashValue {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getHashValue();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setHashValue((Number)value);
            }
        }
        ,
        OldStatus {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getOldStatus();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setOldStatus((Number)value);
            }
        }
        ,
        CompareStatus {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getCompareStatus();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setCompareStatus((Number)value);
            }
        }
        ,
        CompareDate {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getCompareDate();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setCompareDate((Date)value);
            }
        }
        ,
        ObjId {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getObjId();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setObjId((Number)value);
            }
        }
        ,
        PostIndex {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getPostIndex();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setPostIndex((String)value);
            }
        }
        ,
        DeleteRow {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getDeleteRow();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setDeleteRow((Boolean)value);
            }
        }
        ,
        TypeAddressesView1 {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getTypeAddressesView1();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CountryView1 {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getCountryView1();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RegionView1 {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getRegionView1();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RegionDeptView1 {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getRegionDeptView1();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TownVillageView1 {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getTownVillageView1();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StreetsView1 {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getStreetsView1();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AdmDistrictView1 {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getAdmDistrictView1();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MunDistrictView1 {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getMunDistrictView1();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PoliceDeptView1 {
            public Object get(EntAddressesViewRowImpl obj) {
                return obj.getPoliceDeptView1();
            }

            public void put(EntAddressesViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(EntAddressesViewRowImpl object);

        public abstract void put(EntAddressesViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int STATE = AttributesEnum.State.index();
    public static final int INSERTED = AttributesEnum.Inserted.index();
    public static final int INSERTEDBY = AttributesEnum.InsertedBy.index();
    public static final int UPDATED = AttributesEnum.Updated.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int EPID = AttributesEnum.EpId.index();
    public static final int REGIONCODE = AttributesEnum.RegionCode.index();
    public static final int COUNTRYCODE = AttributesEnum.CountryCode.index();
    public static final int TYPEADDR = AttributesEnum.TypeAddr.index();
    public static final int REGIONDEPT = AttributesEnum.RegionDept.index();
    public static final int TOWN = AttributesEnum.Town.index();
    public static final int STREET = AttributesEnum.Street.index();
    public static final int HOUSE = AttributesEnum.House.index();
    public static final int CORPUS = AttributesEnum.Corpus.index();
    public static final int ROOM = AttributesEnum.Room.index();
    public static final int ADMDISTRICT = AttributesEnum.AdmDistrict.index();
    public static final int MUNDISTRICT = AttributesEnum.MunDistrict.index();
    public static final int POLICE = AttributesEnum.Police.index();
    public static final int PHONE = AttributesEnum.Phone.index();
    public static final int UPDATEDFLAG = AttributesEnum.UpdatedFlag.index();
    public static final int SDATE = AttributesEnum.SDate.index();
    public static final int EDATE = AttributesEnum.EDate.index();
    public static final int STRADRS = AttributesEnum.StrAdrs.index();
    public static final int WH = AttributesEnum.Wh.index();
    public static final int PROPISKA = AttributesEnum.Propiska.index();
    public static final int HASHVALUE = AttributesEnum.HashValue.index();
    public static final int OLDSTATUS = AttributesEnum.OldStatus.index();
    public static final int COMPARESTATUS = AttributesEnum.CompareStatus.index();
    public static final int COMPAREDATE = AttributesEnum.CompareDate.index();
    public static final int OBJID = AttributesEnum.ObjId.index();
    public static final int POSTINDEX = AttributesEnum.PostIndex.index();
    public static final int DELETEROW = AttributesEnum.DeleteRow.index();
    public static final int TYPEADDRESSESVIEW1 = AttributesEnum.TypeAddressesView1.index();
    public static final int COUNTRYVIEW1 = AttributesEnum.CountryView1.index();
    public static final int REGIONVIEW1 = AttributesEnum.RegionView1.index();
    public static final int REGIONDEPTVIEW1 = AttributesEnum.RegionDeptView1.index();
    public static final int TOWNVILLAGEVIEW1 = AttributesEnum.TownVillageView1.index();
    public static final int STREETSVIEW1 = AttributesEnum.StreetsView1.index();
    public static final int ADMDISTRICTVIEW1 = AttributesEnum.AdmDistrictView1.index();
    public static final int MUNDISTRICTVIEW1 = AttributesEnum.MunDistrictView1.index();
    public static final int POLICEDEPTVIEW1 = AttributesEnum.PoliceDeptView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EntAddressesViewRowImpl() {
    }

    /**
     * Gets EntAddresses entity object.
     * @return the EntAddresses
     */
    public EntityImpl getEntAddresses() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for STATE using the alias name State.
     * @return the STATE
     */
    public Number getState() {
        return (Number) getAttributeInternal(STATE);
    }

    /**
     * Sets <code>value</code> as attribute value for STATE using the alias name State.
     * @param value value to set the STATE
     */
    public void setState(Number value) {
        setAttributeInternal(STATE, value);
    }

    /**
     * Gets the attribute value for INSERTED using the alias name Inserted.
     * @return the INSERTED
     */
    public Date getInserted() {
        return (Date) getAttributeInternal(INSERTED);
    }

    /**
     * Sets <code>value</code> as attribute value for INSERTED using the alias name Inserted.
     * @param value value to set the INSERTED
     */
    public void setInserted(Date value) {
        setAttributeInternal(INSERTED, value);
    }

    /**
     * Gets the attribute value for INSERTED_BY using the alias name InsertedBy.
     * @return the INSERTED_BY
     */
    public Number getInsertedBy() {
        return (Number) getAttributeInternal(INSERTEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for INSERTED_BY using the alias name InsertedBy.
     * @param value value to set the INSERTED_BY
     */
    public void setInsertedBy(Number value) {
        setAttributeInternal(INSERTEDBY, value);
    }

    /**
     * Gets the attribute value for UPDATED using the alias name Updated.
     * @return the UPDATED
     */
    public Date getUpdated() {
        return (Date) getAttributeInternal(UPDATED);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED using the alias name Updated.
     * @param value value to set the UPDATED
     */
    public void setUpdated(Date value) {
        setAttributeInternal(UPDATED, value);
    }

    /**
     * Gets the attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @return the UPDATED_BY
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @param value value to set the UPDATED_BY
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for EP_ID using the alias name EpId.
     * @return the EP_ID
     */
    public Number getEpId() {
        return (Number) getAttributeInternal(EPID);
    }

    /**
     * Sets <code>value</code> as attribute value for EP_ID using the alias name EpId.
     * @param value value to set the EP_ID
     */
    public void setEpId(Number value) {
        setAttributeInternal(EPID, value);
    }

    /**
     * Gets the attribute value for REGION_CODE using the alias name RegionCode.
     * @return the REGION_CODE
     */
    public Number getRegionCode() {
        return (Number) getAttributeInternal(REGIONCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for REGION_CODE using the alias name RegionCode.
     * @param value value to set the REGION_CODE
     */
    public void setRegionCode(Number value) {
        setAttributeInternal(REGIONCODE, value);
    }

    /**
     * Gets the attribute value for COUNTRY_CODE using the alias name CountryCode.
     * @return the COUNTRY_CODE
     */
    public Number getCountryCode() {
        return (Number) getAttributeInternal(COUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY_CODE using the alias name CountryCode.
     * @param value value to set the COUNTRY_CODE
     */
    public void setCountryCode(Number value) {
        setAttributeInternal(COUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for TYPE_ADDR using the alias name TypeAddr.
     * @return the TYPE_ADDR
     */
    public String getTypeAddr() {
        return (String) getAttributeInternal(TYPEADDR);
    }

    /**
     * Sets <code>value</code> as attribute value for TYPE_ADDR using the alias name TypeAddr.
     * @param value value to set the TYPE_ADDR
     */
    public void setTypeAddr(String value) {
        setAttributeInternal(TYPEADDR, value);
    }

    /**
     * Gets the attribute value for REGION_DEPT using the alias name RegionDept.
     * @return the REGION_DEPT
     */
    public String getRegionDept() {
        return (String) getAttributeInternal(REGIONDEPT);
    }

    /**
     * Sets <code>value</code> as attribute value for REGION_DEPT using the alias name RegionDept.
     * @param value value to set the REGION_DEPT
     */
    public void setRegionDept(String value) {
        setAttributeInternal(REGIONDEPT, value);
    }

    /**
     * Gets the attribute value for TOWN using the alias name Town.
     * @return the TOWN
     */
    public String getTown() {
        return (String) getAttributeInternal(TOWN);
    }

    /**
     * Sets <code>value</code> as attribute value for TOWN using the alias name Town.
     * @param value value to set the TOWN
     */
    public void setTown(String value) {
        setAttributeInternal(TOWN, value);
    }

    /**
     * Gets the attribute value for STREET using the alias name Street.
     * @return the STREET
     */
    public String getStreet() {
        return (String) getAttributeInternal(STREET);
    }

    /**
     * Sets <code>value</code> as attribute value for STREET using the alias name Street.
     * @param value value to set the STREET
     */
    public void setStreet(String value) {
        setAttributeInternal(STREET, value);
    }

    /**
     * Gets the attribute value for HOUSE using the alias name House.
     * @return the HOUSE
     */
    public String getHouse() {
        return (String) getAttributeInternal(HOUSE);
    }

    /**
     * Sets <code>value</code> as attribute value for HOUSE using the alias name House.
     * @param value value to set the HOUSE
     */
    public void setHouse(String value) {
        setAttributeInternal(HOUSE, value);
    }

    /**
     * Gets the attribute value for CORPUS using the alias name Corpus.
     * @return the CORPUS
     */
    public String getCorpus() {
        return (String) getAttributeInternal(CORPUS);
    }

    /**
     * Sets <code>value</code> as attribute value for CORPUS using the alias name Corpus.
     * @param value value to set the CORPUS
     */
    public void setCorpus(String value) {
        setAttributeInternal(CORPUS, value);
    }

    /**
     * Gets the attribute value for ROOM using the alias name Room.
     * @return the ROOM
     */
    public String getRoom() {
        return (String) getAttributeInternal(ROOM);
    }

    /**
     * Sets <code>value</code> as attribute value for ROOM using the alias name Room.
     * @param value value to set the ROOM
     */
    public void setRoom(String value) {
        setAttributeInternal(ROOM, value);
    }

    /**
     * Gets the attribute value for ADM_DISTRICT using the alias name AdmDistrict.
     * @return the ADM_DISTRICT
     */
    public String getAdmDistrict() {
        return (String) getAttributeInternal(ADMDISTRICT);
    }

    /**
     * Sets <code>value</code> as attribute value for ADM_DISTRICT using the alias name AdmDistrict.
     * @param value value to set the ADM_DISTRICT
     */
    public void setAdmDistrict(String value) {
        setAttributeInternal(ADMDISTRICT, value);
    }

    /**
     * Gets the attribute value for MUN_DISTRICT using the alias name MunDistrict.
     * @return the MUN_DISTRICT
     */
    public String getMunDistrict() {
        return (String) getAttributeInternal(MUNDISTRICT);
    }

    /**
     * Sets <code>value</code> as attribute value for MUN_DISTRICT using the alias name MunDistrict.
     * @param value value to set the MUN_DISTRICT
     */
    public void setMunDistrict(String value) {
        setAttributeInternal(MUNDISTRICT, value);
    }

    /**
     * Gets the attribute value for POLICE using the alias name Police.
     * @return the POLICE
     */
    public String getPolice() {
        return (String) getAttributeInternal(POLICE);
    }

    /**
     * Sets <code>value</code> as attribute value for POLICE using the alias name Police.
     * @param value value to set the POLICE
     */
    public void setPolice(String value) {
        setAttributeInternal(POLICE, value);
    }

    /**
     * Gets the attribute value for PHONE using the alias name Phone.
     * @return the PHONE
     */
    public String getPhone() {
        return (String) getAttributeInternal(PHONE);
    }

    /**
     * Sets <code>value</code> as attribute value for PHONE using the alias name Phone.
     * @param value value to set the PHONE
     */
    public void setPhone(String value) {
        setAttributeInternal(PHONE, value);
    }

    /**
     * Gets the attribute value for UPDATED_FLAG using the alias name UpdatedFlag.
     * @return the UPDATED_FLAG
     */
    public Number getUpdatedFlag() {
        return (Number) getAttributeInternal(UPDATEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_FLAG using the alias name UpdatedFlag.
     * @param value value to set the UPDATED_FLAG
     */
    public void setUpdatedFlag(Number value) {
        setAttributeInternal(UPDATEDFLAG, value);
    }

    /**
     * Gets the attribute value for S_DATE using the alias name SDate.
     * @return the S_DATE
     */
    public Date getSDate() {
        return (Date) getAttributeInternal(SDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for S_DATE using the alias name SDate.
     * @param value value to set the S_DATE
     */
    public void setSDate(Date value) {
        setAttributeInternal(SDATE, value);
    }

    /**
     * Gets the attribute value for E_DATE using the alias name EDate.
     * @return the E_DATE
     */
    public Date getEDate() {
        return (Date) getAttributeInternal(EDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for E_DATE using the alias name EDate.
     * @param value value to set the E_DATE
     */
    public void setEDate(Date value) {
        setAttributeInternal(EDATE, value);
    }

    /**
     * Gets the attribute value for STR_ADRS using the alias name StrAdrs.
     * @return the STR_ADRS
     */
    public String getStrAdrs() {
        return (String) getAttributeInternal(STRADRS);
    }

    /**
     * Sets <code>value</code> as attribute value for STR_ADRS using the alias name StrAdrs.
     * @param value value to set the STR_ADRS
     */
    public void setStrAdrs(String value) {
        setAttributeInternal(STRADRS, value);
    }

    /**
     * Gets the attribute value for WH using the alias name Wh.
     * @return the WH
     */
    public String getWh() {
        return (String) getAttributeInternal(WH);
    }

    /**
     * Sets <code>value</code> as attribute value for WH using the alias name Wh.
     * @param value value to set the WH
     */
    public void setWh(String value) {
        setAttributeInternal(WH, value);
    }

    /**
     * Gets the attribute value for PROPISKA using the alias name Propiska.
     * @return the PROPISKA
     */
    public Date getPropiska() {
        return (Date) getAttributeInternal(PROPISKA);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPISKA using the alias name Propiska.
     * @param value value to set the PROPISKA
     */
    public void setPropiska(Date value) {
        setAttributeInternal(PROPISKA, value);
    }

    /**
     * Gets the attribute value for HASH_VALUE using the alias name HashValue.
     * @return the HASH_VALUE
     */
    public Number getHashValue() {
        return (Number) getAttributeInternal(HASHVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for HASH_VALUE using the alias name HashValue.
     * @param value value to set the HASH_VALUE
     */
    public void setHashValue(Number value) {
        setAttributeInternal(HASHVALUE, value);
    }

    /**
     * Gets the attribute value for OLD_STATUS using the alias name OldStatus.
     * @return the OLD_STATUS
     */
    public Number getOldStatus() {
        return (Number) getAttributeInternal(OLDSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for OLD_STATUS using the alias name OldStatus.
     * @param value value to set the OLD_STATUS
     */
    public void setOldStatus(Number value) {
        setAttributeInternal(OLDSTATUS, value);
    }

    /**
     * Gets the attribute value for COMPARE_STATUS using the alias name CompareStatus.
     * @return the COMPARE_STATUS
     */
    public Number getCompareStatus() {
        return (Number) getAttributeInternal(COMPARESTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPARE_STATUS using the alias name CompareStatus.
     * @param value value to set the COMPARE_STATUS
     */
    public void setCompareStatus(Number value) {
        setAttributeInternal(COMPARESTATUS, value);
    }

    /**
     * Gets the attribute value for COMPARE_DATE using the alias name CompareDate.
     * @return the COMPARE_DATE
     */
    public Date getCompareDate() {
        return (Date) getAttributeInternal(COMPAREDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPARE_DATE using the alias name CompareDate.
     * @param value value to set the COMPARE_DATE
     */
    public void setCompareDate(Date value) {
        setAttributeInternal(COMPAREDATE, value);
    }

    /**
     * Gets the attribute value for OBJ_ID using the alias name ObjId.
     * @return the OBJ_ID
     */
    public Number getObjId() {
        return (Number) getAttributeInternal(OBJID);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJ_ID using the alias name ObjId.
     * @param value value to set the OBJ_ID
     */
    public void setObjId(Number value) {
        setAttributeInternal(OBJID, value);
    }

    /**
     * Gets the attribute value for POST_INDEX using the alias name PostIndex.
     * @return the POST_INDEX
     */
    public String getPostIndex() {
        return (String) getAttributeInternal(POSTINDEX);
    }

    /**
     * Sets <code>value</code> as attribute value for POST_INDEX using the alias name PostIndex.
     * @param value value to set the POST_INDEX
     */
    public void setPostIndex(String value) {
        setAttributeInternal(POSTINDEX, value);
    }

    /**
     * Gets the attribute value for DELETE_ROW using the alias name DeleteRow.
     * @return the DELETE_ROW
     */
    public Boolean getDeleteRow() {
        return (Boolean) getAttributeInternal(DELETEROW);
    }

    /**
     * Sets <code>value</code> as attribute value for DELETE_ROW using the alias name DeleteRow.
     * @param value value to set the DELETE_ROW
     */
    public void setDeleteRow(Boolean value) {
        setAttributeInternal(DELETEROW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TypeAddressesView1.
     */
    public RowSet getTypeAddressesView1() {
        return (RowSet)getAttributeInternal(TYPEADDRESSESVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountryView1.
     */
    public RowSet getCountryView1() {
        return (RowSet)getAttributeInternal(COUNTRYVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RegionView1.
     */
    public RowSet getRegionView1() {
        return (RowSet)getAttributeInternal(REGIONVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RegionDeptView1.
     */
    public RowSet getRegionDeptView1() {
        return (RowSet)getAttributeInternal(REGIONDEPTVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TownVillageView1.
     */
    public RowSet getTownVillageView1() {
        return (RowSet)getAttributeInternal(TOWNVILLAGEVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StreetsView1.
     */
    public RowSet getStreetsView1() {
        return (RowSet)getAttributeInternal(STREETSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AdmDistrictView1.
     */
    public RowSet getAdmDistrictView1() {
        return (RowSet)getAttributeInternal(ADMDISTRICTVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MunDistrictView1.
     */
    public RowSet getMunDistrictView1() {
        return (RowSet)getAttributeInternal(MUNDISTRICTVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PoliceDeptView1.
     */
    public RowSet getPoliceDeptView1() {
        return (RowSet)getAttributeInternal(POLICEDEPTVIEW1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
