package ru.rdtex.mvd.weapon.model.vo;

import javax.annotation.PostConstruct;

import oracle.adf.model.binding.DCBindingContainer;

import oracle.adf.model.binding.DCIteratorBinding;

import oracle.binding.BindingContainer;
import oracle.binding.OperationBinding;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;

import ru.rdtex.mvd.weapon.global.JSFUtils;
import ru.rdtex.mvd.weapon.model.vo.common.EntPersonsView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 29 15:55:45 MSD 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EntPersonsViewImpl extends ViewObjectImpl implements EntPersonsView {
    /**
     * This is the default constructor (do not remove).
     */
    public EntPersonsViewImpl() {
        super();
    }


    /**
     * Returns the variable value for fid.
     * @return variable value for fid
     */
    public Integer getfid() {
        return (Integer)ensureVariableManager().getVariableValue("fid");
    }

    /**
     * Sets <code>value</code> for variable fid.
     * @param value value to bind as fid
     */
    public void setfid(Integer value) {
        ensureVariableManager().setVariableValue("fid", value);
    }

    /**
     * Returns the variable value for fio.
     * @return variable value for fio
     */
    public String getfio() {
        return (String)ensureVariableManager().getVariableValue("fio");
    }

    /**
     * Sets <code>value</code> for variable fio.
     * @param value value to bind as fio
     */
    public void setfio(String value) {
        ensureVariableManager().setVariableValue("fio", value);
    }

    /**
     * Returns the variable value for fname.
     * @return variable value for fname
     */
    public String getfname() {
        return (String)ensureVariableManager().getVariableValue("fname");
    }

    /**
     * Sets <code>value</code> for variable fname.
     * @param value value to bind as fname
     */
    public void setfname(String value) {
        ensureVariableManager().setVariableValue("fname", value);
    }

    /**
     * Returns the variable value for fotchestvo.
     * @return variable value for fotchestvo
     */
    public String getfotchestvo() {
        return (String)ensureVariableManager().getVariableValue("fotchestvo");
    }

    /**
     * Sets <code>value</code> for variable fotchestvo.
     * @param value value to bind as fotchestvo
     */
    public void setfotchestvo(String value) {
        ensureVariableManager().setVariableValue("fotchestvo", value);
    }

    /**
     * Returns the variable value for fbirthday_s.
     * @return variable value for fbirthday_s
     */
    public Date getfbirthday_s() {
        return (Date)ensureVariableManager().getVariableValue("fbirthday_s");
    }

    /**
     * Sets <code>value</code> for variable fbirthday_s.
     * @param value value to bind as fbirthday_s
     */
    public void setfbirthday_s(Date value) {
        ensureVariableManager().setVariableValue("fbirthday_s", value);
    }

    /**
     * Returns the variable value for fbirthday_e.
     * @return variable value for fbirthday_e
     */
    public Date getfbirthday_e() {
        return (Date)ensureVariableManager().getVariableValue("fbirthday_e");
    }

    /**
     * Sets <code>value</code> for variable fbirthday_e.
     * @param value value to bind as fbirthday_e
     */
    public void setfbirthday_e(Date value) {
        ensureVariableManager().setVariableValue("fbirthday_e", value);
    }

    /**
     * Returns the variable value for fvip.
     * @return variable value for fvip
     */
    public String getfvip() {
        return (String)ensureVariableManager().getVariableValue("fvip");
    }

    /**
     * Sets <code>value</code> for variable fvip.
     * @param value value to bind as fvip
     */
    public void setfvip(String value) {
        ensureVariableManager().setVariableValue("fvip", value);
    }

    /**
     * Returns the variable value for finn.
     * @return variable value for finn
     */
    public String getfinn() {
        return (String)ensureVariableManager().getVariableValue("finn");
    }

    /**
     * Sets <code>value</code> for variable finn.
     * @param value value to bind as finn
     */
    public void setfinn(String value) {
        ensureVariableManager().setVariableValue("finn", value);
    }

    /**
     * Returns the variable value for fowner.
     * @return variable value for fowner
     */
    public String getfowner() {
        return (String)ensureVariableManager().getVariableValue("fowner");
    }

    /**
     * Sets <code>value</code> for variable fowner.
     * @param value value to bind as fowner
     */
    public void setfowner(String value) {
        ensureVariableManager().setVariableValue("fowner", value);
    }

    /**
     * Returns the bind variable value for fguard.
     * @return bind variable value for fguard
     */
    public String getfguard() {
        return (String)getNamedWhereClauseParam("fguard");
    }

    /**
     * Sets <code>value</code> for bind variable fguard.
     * @param value value to bind as fguard
     */
    public void setfguard(String value) {
        setNamedWhereClauseParam("fguard", value);
    }

    /**
     * Returns the bind variable value for femployee.
     * @return bind variable value for femployee
     */
    public String getfemployee() {
        return (String)getNamedWhereClauseParam("femployee");
    }

    /**
     * Sets <code>value</code> for bind variable femployee.
     * @param value value to bind as femployee
     */
    public void setfemployee(String value) {
        setNamedWhereClauseParam("femployee", value);
    }


    /**
     * Returns the bind variable value for fstate.
     * @return bind variable value for fstate
     */
    public Integer getfstate() {
        return (Integer)getNamedWhereClauseParam("fstate");
    }

    /**
     * Sets <code>value</code> for bind variable fstate.
     * @param value value to bind as fstate
     */
    public void setfstate(Integer value) {
        setNamedWhereClauseParam("fstate", value);
    }

    
    /**
     * Sample method that if invoked deletes all rows that have the
     * MarekedForDelete transient attribute set to true
     */
    public void deleteSelectedRows() {
        //create a second row set to not impact the row set
        //used in ADF
        RowSet duplicateRowSet = this.createRowSet("duplicateRowSet");
        //set rowset to first row to avoid "attempt to access
        //dead row" exception
        duplicateRowSet.first();
        //get the current row of the table to set it back after
        //re-executing the VO
        Row currentRow = this.getCurrentRow();
        boolean currentRowDeleted = false;
        //get all rows that have the transoent attribute
        //"MarkForDelete" set to true
        Row[] rowsToDelete =
            duplicateRowSet.getFilteredRows("DeleteRow", true);
        if (rowsToDelete.length > 0) {
            //only run throizgh this code if there is something to
            //delete
            for (Row rw : rowsToDelete) {
                //if row is ts marked as the current in VO, set
                //boolean flag
                if (rw.getKey().equals(currentRow.getKey())) {
                    currentRowDeleted = true;
                }
                //remove row - don't yet commit
                rw.remove();
            }
            //re-execute VO
            this.executeQuery();
            //reset current row if it hasn't been deleted
            if (!currentRowDeleted) {
                this.setCurrentRow(currentRow);
            }
            
            duplicateRowSet.closeRowSet();
        }
    }

    /**
     * Returns the bind variable value for personType.
     * @return bind variable value for personType
     */
    public String getpersonType() {
        return (String)getNamedWhereClauseParam("personType");
    }

    /**
     * Sets <code>value</code> for bind variable personType.
     * @param value value to bind as personType
     */
    public void setpersonType(String value) {
        setNamedWhereClauseParam("personType", value);
    }
    
}
