package ru.rdtex.mvd.weapon.model.vo;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;

import ru.rdtex.mvd.weapon.global.JSFUtils;
import ru.rdtex.mvd.weapon.model.en.EntPersonsImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 29 15:55:44 MSD 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EntPersonsViewRowImpl extends ViewRowImpl {
    private Boolean deleteRow;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CountryCode {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getCountryCode();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setCountryCode((Number)value);
            }
        }
        ,
        TypedocCode {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getTypedocCode();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setTypedocCode((Number)value);
            }
        }
        ,
        PtypeCode {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getPtypeCode();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setPtypeCode((Number)value);
            }
        }
        ,
        ArcFio {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getArcFio();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setArcFio((String)value);
            }
        }
        ,
        Name {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getName();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setName((String)value);
            }
        }
        ,
        Otchestvo {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getOtchestvo();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setOtchestvo((String)value);
            }
        }
        ,
        JobTittle {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getJobTittle();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setJobTittle((String)value);
            }
        }
        ,
        BirthAdr {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getBirthAdr();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setBirthAdr((String)value);
            }
        }
        ,
        JobPost {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getJobPost();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setJobPost((String)value);
            }
        }
        ,
        JobPhone {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getJobPhone();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setJobPhone((String)value);
            }
        }
        ,
        EpId {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getEpId();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setEpId((Number)value);
            }
        }
        ,
        Id {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getId();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        Inn {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getInn();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setInn((String)value);
            }
        }
        ,
        DocSer {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getDocSer();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setDocSer((String)value);
            }
        }
        ,
        DocNum {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getDocNum();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setDocNum((String)value);
            }
        }
        ,
        DocDate {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getDocDate();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setDocDate((Date)value);
            }
        }
        ,
        DocOrg {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getDocOrg();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setDocOrg((String)value);
            }
        }
        ,
        UpdatedFlag {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getUpdatedFlag();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setUpdatedFlag((Number)value);
            }
        }
        ,
        Sex {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getSex();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setSex((String)value);
            }
        }
        ,
        Nationality {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getNationality();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setNationality((String)value);
            }
        }
        ,
        Birthday {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getBirthday();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setBirthday((Date)value);
            }
        }
        ,
        State {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getState();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setState((Number)value);
            }
        }
        ,
        Inserted {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getInserted();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setInserted((Date)value);
            }
        }
        ,
        InsertedBy {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getInsertedBy();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setInsertedBy((Number)value);
            }
        }
        ,
        TitleSurname {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getTitleSurname();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setTitleSurname((String)value);
            }
        }
        ,
        Updated {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getUpdated();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setUpdated((Date)value);
            }
        }
        ,
        UpdatedBy {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getUpdatedBy();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setUpdatedBy((Number)value);
            }
        }
        ,
        RegionCode {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getRegionCode();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setRegionCode((Number)value);
            }
        }
        ,
        OkrugCode {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getOkrugCode();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setOkrugCode((Number)value);
            }
        }
        ,
        DepTypeCode {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getDepTypeCode();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setDepTypeCode((Number)value);
            }
        }
        ,
        RegSertDate {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getRegSertDate();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setRegSertDate((Date)value);
            }
        }
        ,
        CharterDate {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getCharterDate();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setCharterDate((Date)value);
            }
        }
        ,
        TaxDate {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getTaxDate();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setTaxDate((Date)value);
            }
        }
        ,
        OtherDate {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getOtherDate();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setOtherDate((Date)value);
            }
        }
        ,
        EpType {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getEpType();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setEpType((String)value);
            }
        }
        ,
        ObjId {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getObjId();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setObjId((Number)value);
            }
        }
        ,
        ArcReason {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getArcReason();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setArcReason((String)value);
            }
        }
        ,
        ArcDate {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getArcDate();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setArcDate((Date)value);
            }
        }
        ,
        Wh {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getWh();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setWh((String)value);
            }
        }
        ,
        ArcIdDate {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getArcIdDate();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setArcIdDate((Date)value);
            }
        }
        ,
        SupervisCase {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getSupervisCase();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setSupervisCase((String)value);
            }
        }
        ,
        Founders {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getFounders();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setFounders((String)value);
            }
        }
        ,
        MainNumber {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getMainNumber();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setMainNumber((String)value);
            }
        }
        ,
        RegDocName {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getRegDocName();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setRegDocName((String)value);
            }
        }
        ,
        EndRegDocDate {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getEndRegDocDate();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setEndRegDocDate((Date)value);
            }
        }
        ,
        RegDocState {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getRegDocState();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setRegDocState((Number)value);
            }
        }
        ,
        Comments {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getComments();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setComments((String)value);
            }
        }
        ,
        ArcId {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getArcId();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setArcId((String)value);
            }
        }
        ,
        Vip {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getVip();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setVip((Number)value);
            }
        }
        ,
        HashValue {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getHashValue();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setHashValue((Number)value);
            }
        }
        ,
        OldStatus {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getOldStatus();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setOldStatus((Number)value);
            }
        }
        ,
        CompareStatus {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getCompareStatus();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setCompareStatus((Number)value);
            }
        }
        ,
        CompareDate {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getCompareDate();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setCompareDate((Date)value);
            }
        }
        ,
        EMail {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getEMail();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setEMail((String)value);
            }
        }
        ,
        Nationality2 {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getNationality2();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setNationality2((String)value);
            }
        }
        ,
        PsgCase {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getPsgCase();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setPsgCase((String)value);
            }
        }
        ,
        ArcComments {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getArcComments();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setArcComments((String)value);
            }
        }
        ,
        PsgType {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getPsgType();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setPsgType((String)value);
            }
        }
        ,
        IsOwner {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getIsOwner();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setIsOwner((String)value);
            }
        }
        ,
        IsGuard {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getIsGuard();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setIsGuard((String)value);
            }
        }
        ,
        IsEmployee {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getIsEmployee();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setIsEmployee((String)value);
            }
        }
        ,
        LrrState {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getLrrState();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setLrrState((Number)value);
            }
        }
        ,
        Phone {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getPhone();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setPhone((String)value);
            }
        }
        ,
        DeleteRow {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getDeleteRow();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setDeleteRow((Boolean)value);
            }
        }
        ,
        EntPersonsView {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getEntPersonsView();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EntAddressesView {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getEntAddressesView();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DocRelationsView {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getDocRelationsView();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RPersonGunsView {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getRPersonGunsView();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EntPersonsRovdView {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getEntPersonsRovdView();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EntPhotoView {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getEntPhotoView();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        VSuperDocView {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getVSuperDocView();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CountryView1 {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getCountryView1();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TypeDocView1 {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getTypeDocView1();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TypePersonView1 {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getTypePersonView1();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        YesNo10_1 {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getYesNo10_1();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AcsUsersView2 {
            public Object get(EntPersonsViewRowImpl obj) {
                return obj.getAcsUsersView2();
            }

            public void put(EntPersonsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(EntPersonsViewRowImpl object);

        public abstract void put(EntPersonsViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int COUNTRYCODE = AttributesEnum.CountryCode.index();
    public static final int TYPEDOCCODE = AttributesEnum.TypedocCode.index();
    public static final int PTYPECODE = AttributesEnum.PtypeCode.index();
    public static final int ARCFIO = AttributesEnum.ArcFio.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int OTCHESTVO = AttributesEnum.Otchestvo.index();
    public static final int JOBTITTLE = AttributesEnum.JobTittle.index();
    public static final int BIRTHADR = AttributesEnum.BirthAdr.index();
    public static final int JOBPOST = AttributesEnum.JobPost.index();
    public static final int JOBPHONE = AttributesEnum.JobPhone.index();
    public static final int EPID = AttributesEnum.EpId.index();
    public static final int ID = AttributesEnum.Id.index();
    public static final int INN = AttributesEnum.Inn.index();
    public static final int DOCSER = AttributesEnum.DocSer.index();
    public static final int DOCNUM = AttributesEnum.DocNum.index();
    public static final int DOCDATE = AttributesEnum.DocDate.index();
    public static final int DOCORG = AttributesEnum.DocOrg.index();
    public static final int UPDATEDFLAG = AttributesEnum.UpdatedFlag.index();
    public static final int SEX = AttributesEnum.Sex.index();
    public static final int NATIONALITY = AttributesEnum.Nationality.index();
    public static final int BIRTHDAY = AttributesEnum.Birthday.index();
    public static final int STATE = AttributesEnum.State.index();
    public static final int INSERTED = AttributesEnum.Inserted.index();
    public static final int INSERTEDBY = AttributesEnum.InsertedBy.index();
    public static final int TITLESURNAME = AttributesEnum.TitleSurname.index();
    public static final int UPDATED = AttributesEnum.Updated.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int REGIONCODE = AttributesEnum.RegionCode.index();
    public static final int OKRUGCODE = AttributesEnum.OkrugCode.index();
    public static final int DEPTYPECODE = AttributesEnum.DepTypeCode.index();
    public static final int REGSERTDATE = AttributesEnum.RegSertDate.index();
    public static final int CHARTERDATE = AttributesEnum.CharterDate.index();
    public static final int TAXDATE = AttributesEnum.TaxDate.index();
    public static final int OTHERDATE = AttributesEnum.OtherDate.index();
    public static final int EPTYPE = AttributesEnum.EpType.index();
    public static final int OBJID = AttributesEnum.ObjId.index();
    public static final int ARCREASON = AttributesEnum.ArcReason.index();
    public static final int ARCDATE = AttributesEnum.ArcDate.index();
    public static final int WH = AttributesEnum.Wh.index();
    public static final int ARCIDDATE = AttributesEnum.ArcIdDate.index();
    public static final int SUPERVISCASE = AttributesEnum.SupervisCase.index();
    public static final int FOUNDERS = AttributesEnum.Founders.index();
    public static final int MAINNUMBER = AttributesEnum.MainNumber.index();
    public static final int REGDOCNAME = AttributesEnum.RegDocName.index();
    public static final int ENDREGDOCDATE = AttributesEnum.EndRegDocDate.index();
    public static final int REGDOCSTATE = AttributesEnum.RegDocState.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int ARCID = AttributesEnum.ArcId.index();
    public static final int VIP = AttributesEnum.Vip.index();
    public static final int HASHVALUE = AttributesEnum.HashValue.index();
    public static final int OLDSTATUS = AttributesEnum.OldStatus.index();
    public static final int COMPARESTATUS = AttributesEnum.CompareStatus.index();
    public static final int COMPAREDATE = AttributesEnum.CompareDate.index();
    public static final int EMAIL = AttributesEnum.EMail.index();
    public static final int NATIONALITY2 = AttributesEnum.Nationality2.index();
    public static final int PSGCASE = AttributesEnum.PsgCase.index();
    public static final int ARCCOMMENTS = AttributesEnum.ArcComments.index();
    public static final int PSGTYPE = AttributesEnum.PsgType.index();
    public static final int ISOWNER = AttributesEnum.IsOwner.index();
    public static final int ISGUARD = AttributesEnum.IsGuard.index();
    public static final int ISEMPLOYEE = AttributesEnum.IsEmployee.index();
    public static final int LRRSTATE = AttributesEnum.LrrState.index();
    public static final int PHONE = AttributesEnum.Phone.index();
    public static final int DELETEROW = AttributesEnum.DeleteRow.index();
    public static final int ENTPERSONSVIEW = AttributesEnum.EntPersonsView.index();
    public static final int ENTADDRESSESVIEW = AttributesEnum.EntAddressesView.index();
    public static final int DOCRELATIONSVIEW = AttributesEnum.DocRelationsView.index();
    public static final int RPERSONGUNSVIEW = AttributesEnum.RPersonGunsView.index();
    public static final int ENTPERSONSROVDVIEW = AttributesEnum.EntPersonsRovdView.index();
    public static final int ENTPHOTOVIEW = AttributesEnum.EntPhotoView.index();
    public static final int VSUPERDOCVIEW = AttributesEnum.VSuperDocView.index();
    public static final int COUNTRYVIEW1 = AttributesEnum.CountryView1.index();
    public static final int TYPEDOCVIEW1 = AttributesEnum.TypeDocView1.index();
    public static final int TYPEPERSONVIEW1 = AttributesEnum.TypePersonView1.index();
    public static final int YESNO10_1 = AttributesEnum.YesNo10_1.index();
    public static final int ACSUSERSVIEW2 = AttributesEnum.AcsUsersView2.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EntPersonsViewRowImpl() {
        
    }

    /**
     * Gets EntPersons entity object.
     * @return the EntPersons
     */
    public EntPersonsImpl getEntPersons() {
        return (EntPersonsImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for COUNTRY_CODE using the alias name CountryCode.
     * @return the COUNTRY_CODE
     */
    public Number getCountryCode() {
        return (Number) getAttributeInternal(COUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY_CODE using the alias name CountryCode.
     * @param value value to set the COUNTRY_CODE
     */
    public void setCountryCode(Number value) {
        setAttributeInternal(COUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for TYPEDOC_CODE using the alias name TypedocCode.
     * @return the TYPEDOC_CODE
     */
    public Number getTypedocCode() {
        return (Number) getAttributeInternal(TYPEDOCCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TYPEDOC_CODE using the alias name TypedocCode.
     * @param value value to set the TYPEDOC_CODE
     */
    public void setTypedocCode(Number value) {
        setAttributeInternal(TYPEDOCCODE, value);
    }

    /**
     * Gets the attribute value for PTYPE_CODE using the alias name PtypeCode.
     * @return the PTYPE_CODE
     */
    public Number getPtypeCode() {
        return (Number) getAttributeInternal(PTYPECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for PTYPE_CODE using the alias name PtypeCode.
     * @param value value to set the PTYPE_CODE
     */
    public void setPtypeCode(Number value) {
        setAttributeInternal(PTYPECODE, value);
    }

    /**
     * Gets the attribute value for ARC_FIO using the alias name ArcFio.
     * @return the ARC_FIO
     */
    public String getArcFio() {
        return (String) getAttributeInternal(ARCFIO);
    }

    /**
     * Sets <code>value</code> as attribute value for ARC_FIO using the alias name ArcFio.
     * @param value value to set the ARC_FIO
     */
    public void setArcFio(String value) {
        setAttributeInternal(ARCFIO, value);
    }

    /**
     * Gets the attribute value for NAME using the alias name Name.
     * @return the NAME
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME using the alias name Name.
     * @param value value to set the NAME
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for OTCHESTVO using the alias name Otchestvo.
     * @return the OTCHESTVO
     */
    public String getOtchestvo() {
        return (String) getAttributeInternal(OTCHESTVO);
    }

    /**
     * Sets <code>value</code> as attribute value for OTCHESTVO using the alias name Otchestvo.
     * @param value value to set the OTCHESTVO
     */
    public void setOtchestvo(String value) {
        setAttributeInternal(OTCHESTVO, value);
    }

    /**
     * Gets the attribute value for JOB_TITTLE using the alias name JobTittle.
     * @return the JOB_TITTLE
     */
    public String getJobTittle() {
        return (String) getAttributeInternal(JOBTITTLE);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_TITTLE using the alias name JobTittle.
     * @param value value to set the JOB_TITTLE
     */
    public void setJobTittle(String value) {
        setAttributeInternal(JOBTITTLE, value);
    }

    /**
     * Gets the attribute value for BIRTH_ADR using the alias name BirthAdr.
     * @return the BIRTH_ADR
     */
    public String getBirthAdr() {
        return (String) getAttributeInternal(BIRTHADR);
    }

    /**
     * Sets <code>value</code> as attribute value for BIRTH_ADR using the alias name BirthAdr.
     * @param value value to set the BIRTH_ADR
     */
    public void setBirthAdr(String value) {
        setAttributeInternal(BIRTHADR, value);
    }

    /**
     * Gets the attribute value for JOB_POST using the alias name JobPost.
     * @return the JOB_POST
     */
    public String getJobPost() {
        return (String) getAttributeInternal(JOBPOST);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_POST using the alias name JobPost.
     * @param value value to set the JOB_POST
     */
    public void setJobPost(String value) {
        setAttributeInternal(JOBPOST, value);
    }

    /**
     * Gets the attribute value for JOB_PHONE using the alias name JobPhone.
     * @return the JOB_PHONE
     */
    public String getJobPhone() {
        return (String) getAttributeInternal(JOBPHONE);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_PHONE using the alias name JobPhone.
     * @param value value to set the JOB_PHONE
     */
    public void setJobPhone(String value) {
        setAttributeInternal(JOBPHONE, value);
    }

    /**
     * Gets the attribute value for EP_ID using the alias name EpId.
     * @return the EP_ID
     */
    public Number getEpId() {
        return (Number) getAttributeInternal(EPID);
    }

    /**
     * Sets <code>value</code> as attribute value for EP_ID using the alias name EpId.
     * @param value value to set the EP_ID
     */
    public void setEpId(Number value) {
        setAttributeInternal(EPID, value);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for INN using the alias name Inn.
     * @return the INN
     */
    public String getInn() {
        return (String) getAttributeInternal(INN);
    }

    /**
     * Sets <code>value</code> as attribute value for INN using the alias name Inn.
     * @param value value to set the INN
     */
    public void setInn(String value) {
        setAttributeInternal(INN, value);
    }

    /**
     * Gets the attribute value for DOC_SER using the alias name DocSer.
     * @return the DOC_SER
     */
    public String getDocSer() {
        return (String) getAttributeInternal(DOCSER);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_SER using the alias name DocSer.
     * @param value value to set the DOC_SER
     */
    public void setDocSer(String value) {
        setAttributeInternal(DOCSER, value);
    }

    /**
     * Gets the attribute value for DOC_NUM using the alias name DocNum.
     * @return the DOC_NUM
     */
    public String getDocNum() {
        return (String) getAttributeInternal(DOCNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_NUM using the alias name DocNum.
     * @param value value to set the DOC_NUM
     */
    public void setDocNum(String value) {
        setAttributeInternal(DOCNUM, value);
    }

    /**
     * Gets the attribute value for DOC_DATE using the alias name DocDate.
     * @return the DOC_DATE
     */
    public Date getDocDate() {
        return (Date) getAttributeInternal(DOCDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_DATE using the alias name DocDate.
     * @param value value to set the DOC_DATE
     */
    public void setDocDate(Date value) {
        setAttributeInternal(DOCDATE, value);
    }

    /**
     * Gets the attribute value for DOC_ORG using the alias name DocOrg.
     * @return the DOC_ORG
     */
    public String getDocOrg() {
        return (String) getAttributeInternal(DOCORG);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_ORG using the alias name DocOrg.
     * @param value value to set the DOC_ORG
     */
    public void setDocOrg(String value) {
        setAttributeInternal(DOCORG, value);
    }

    /**
     * Gets the attribute value for UPDATED_FLAG using the alias name UpdatedFlag.
     * @return the UPDATED_FLAG
     */
    public Number getUpdatedFlag() {
        return (Number) getAttributeInternal(UPDATEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_FLAG using the alias name UpdatedFlag.
     * @param value value to set the UPDATED_FLAG
     */
    public void setUpdatedFlag(Number value) {
        setAttributeInternal(UPDATEDFLAG, value);
    }

    /**
     * Gets the attribute value for SEX using the alias name Sex.
     * @return the SEX
     */
    public String getSex() {
        return (String) getAttributeInternal(SEX);
    }

    /**
     * Sets <code>value</code> as attribute value for SEX using the alias name Sex.
     * @param value value to set the SEX
     */
    public void setSex(String value) {
        setAttributeInternal(SEX, value);
    }

    /**
     * Gets the attribute value for NATIONALITY using the alias name Nationality.
     * @return the NATIONALITY
     */
    public String getNationality() {
        return (String) getAttributeInternal(NATIONALITY);
    }

    /**
     * Sets <code>value</code> as attribute value for NATIONALITY using the alias name Nationality.
     * @param value value to set the NATIONALITY
     */
    public void setNationality(String value) {
        setAttributeInternal(NATIONALITY, value);
    }

    /**
     * Gets the attribute value for BIRTHDAY using the alias name Birthday.
     * @return the BIRTHDAY
     */
    public Date getBirthday() {
        return (Date) getAttributeInternal(BIRTHDAY);
    }

    /**
     * Sets <code>value</code> as attribute value for BIRTHDAY using the alias name Birthday.
     * @param value value to set the BIRTHDAY
     */
    public void setBirthday(Date value) {
        setAttributeInternal(BIRTHDAY, value);
    }

    /**
     * Gets the attribute value for STATE using the alias name State.
     * @return the STATE
     */
    public Number getState() {
        return (Number) getAttributeInternal(STATE);
    }

    /**
     * Sets <code>value</code> as attribute value for STATE using the alias name State.
     * @param value value to set the STATE
     */
    public void setState(Number value) {
        setAttributeInternal(STATE, value);
    }

    /**
     * Gets the attribute value for INSERTED using the alias name Inserted.
     * @return the INSERTED
     */
    public Date getInserted() {
        return (Date) getAttributeInternal(INSERTED);
    }

    /**
     * Sets <code>value</code> as attribute value for INSERTED using the alias name Inserted.
     * @param value value to set the INSERTED
     */
    public void setInserted(Date value) {
        setAttributeInternal(INSERTED, value);
    }

    /**
     * Gets the attribute value for INSERTED_BY using the alias name InsertedBy.
     * @return the INSERTED_BY
     */
    public Number getInsertedBy() {
        return (Number) getAttributeInternal(INSERTEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for INSERTED_BY using the alias name InsertedBy.
     * @param value value to set the INSERTED_BY
     */
    public void setInsertedBy(Number value) {
        setAttributeInternal(INSERTEDBY, value);
    }

    /**
     * Gets the attribute value for TITLE_SURNAME using the alias name TitleSurname.
     * @return the TITLE_SURNAME
     */
    public String getTitleSurname() {
        return (String) getAttributeInternal(TITLESURNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TITLE_SURNAME using the alias name TitleSurname.
     * @param value value to set the TITLE_SURNAME
     */
    public void setTitleSurname(String value) {
        setAttributeInternal(TITLESURNAME, value);
    }

    /**
     * Gets the attribute value for UPDATED using the alias name Updated.
     * @return the UPDATED
     */
    public Date getUpdated() {
        return (Date) getAttributeInternal(UPDATED);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED using the alias name Updated.
     * @param value value to set the UPDATED
     */
    public void setUpdated(Date value) {
        setAttributeInternal(UPDATED, value);
    }

    /**
     * Gets the attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @return the UPDATED_BY
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @param value value to set the UPDATED_BY
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for REGION_CODE using the alias name RegionCode.
     * @return the REGION_CODE
     */
    public Number getRegionCode() {
        return (Number) getAttributeInternal(REGIONCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for REGION_CODE using the alias name RegionCode.
     * @param value value to set the REGION_CODE
     */
    public void setRegionCode(Number value) {
        setAttributeInternal(REGIONCODE, value);
    }

    /**
     * Gets the attribute value for OKRUG_CODE using the alias name OkrugCode.
     * @return the OKRUG_CODE
     */
    public Number getOkrugCode() {
        return (Number) getAttributeInternal(OKRUGCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for OKRUG_CODE using the alias name OkrugCode.
     * @param value value to set the OKRUG_CODE
     */
    public void setOkrugCode(Number value) {
        setAttributeInternal(OKRUGCODE, value);
    }

    /**
     * Gets the attribute value for DEP_TYPE_CODE using the alias name DepTypeCode.
     * @return the DEP_TYPE_CODE
     */
    public Number getDepTypeCode() {
        return (Number) getAttributeInternal(DEPTYPECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for DEP_TYPE_CODE using the alias name DepTypeCode.
     * @param value value to set the DEP_TYPE_CODE
     */
    public void setDepTypeCode(Number value) {
        setAttributeInternal(DEPTYPECODE, value);
    }

    /**
     * Gets the attribute value for REG_SERT_DATE using the alias name RegSertDate.
     * @return the REG_SERT_DATE
     */
    public Date getRegSertDate() {
        return (Date) getAttributeInternal(REGSERTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REG_SERT_DATE using the alias name RegSertDate.
     * @param value value to set the REG_SERT_DATE
     */
    public void setRegSertDate(Date value) {
        setAttributeInternal(REGSERTDATE, value);
    }

    /**
     * Gets the attribute value for CHARTER_DATE using the alias name CharterDate.
     * @return the CHARTER_DATE
     */
    public Date getCharterDate() {
        return (Date) getAttributeInternal(CHARTERDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CHARTER_DATE using the alias name CharterDate.
     * @param value value to set the CHARTER_DATE
     */
    public void setCharterDate(Date value) {
        setAttributeInternal(CHARTERDATE, value);
    }

    /**
     * Gets the attribute value for TAX_DATE using the alias name TaxDate.
     * @return the TAX_DATE
     */
    public Date getTaxDate() {
        return (Date) getAttributeInternal(TAXDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_DATE using the alias name TaxDate.
     * @param value value to set the TAX_DATE
     */
    public void setTaxDate(Date value) {
        setAttributeInternal(TAXDATE, value);
    }

    /**
     * Gets the attribute value for OTHER_DATE using the alias name OtherDate.
     * @return the OTHER_DATE
     */
    public Date getOtherDate() {
        return (Date) getAttributeInternal(OTHERDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHER_DATE using the alias name OtherDate.
     * @param value value to set the OTHER_DATE
     */
    public void setOtherDate(Date value) {
        setAttributeInternal(OTHERDATE, value);
    }

    /**
     * Gets the attribute value for EP_TYPE using the alias name EpType.
     * @return the EP_TYPE
     */
    public String getEpType() {
        return (String) getAttributeInternal(EPTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for EP_TYPE using the alias name EpType.
     * @param value value to set the EP_TYPE
     */
    public void setEpType(String value) {
        setAttributeInternal(EPTYPE, value);
    }

    /**
     * Gets the attribute value for OBJ_ID using the alias name ObjId.
     * @return the OBJ_ID
     */
    public Number getObjId() {
        return (Number) getAttributeInternal(OBJID);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJ_ID using the alias name ObjId.
     * @param value value to set the OBJ_ID
     */
    public void setObjId(Number value) {
        setAttributeInternal(OBJID, value);
    }

    /**
     * Gets the attribute value for ARC_REASON using the alias name ArcReason.
     * @return the ARC_REASON
     */
    public String getArcReason() {
        return (String) getAttributeInternal(ARCREASON);
    }

    /**
     * Sets <code>value</code> as attribute value for ARC_REASON using the alias name ArcReason.
     * @param value value to set the ARC_REASON
     */
    public void setArcReason(String value) {
        setAttributeInternal(ARCREASON, value);
    }

    /**
     * Gets the attribute value for ARC_DATE using the alias name ArcDate.
     * @return the ARC_DATE
     */
    public Date getArcDate() {
        return (Date) getAttributeInternal(ARCDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ARC_DATE using the alias name ArcDate.
     * @param value value to set the ARC_DATE
     */
    public void setArcDate(Date value) {
        setAttributeInternal(ARCDATE, value);
    }

    /**
     * Gets the attribute value for WH using the alias name Wh.
     * @return the WH
     */
    public String getWh() {
        return (String) getAttributeInternal(WH);
    }

    /**
     * Sets <code>value</code> as attribute value for WH using the alias name Wh.
     * @param value value to set the WH
     */
    public void setWh(String value) {
        setAttributeInternal(WH, value);
    }

    /**
     * Gets the attribute value for ARC_ID_DATE using the alias name ArcIdDate.
     * @return the ARC_ID_DATE
     */
    public Date getArcIdDate() {
        return (Date) getAttributeInternal(ARCIDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ARC_ID_DATE using the alias name ArcIdDate.
     * @param value value to set the ARC_ID_DATE
     */
    public void setArcIdDate(Date value) {
        setAttributeInternal(ARCIDDATE, value);
    }

    /**
     * Gets the attribute value for SUPERVIS_CASE using the alias name SupervisCase.
     * @return the SUPERVIS_CASE
     */
    public String getSupervisCase() {
        return (String) getAttributeInternal(SUPERVISCASE);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPERVIS_CASE using the alias name SupervisCase.
     * @param value value to set the SUPERVIS_CASE
     */
    public void setSupervisCase(String value) {
        setAttributeInternal(SUPERVISCASE, value);
    }

    /**
     * Gets the attribute value for FOUNDERS using the alias name Founders.
     * @return the FOUNDERS
     */
    public String getFounders() {
        return (String) getAttributeInternal(FOUNDERS);
    }

    /**
     * Sets <code>value</code> as attribute value for FOUNDERS using the alias name Founders.
     * @param value value to set the FOUNDERS
     */
    public void setFounders(String value) {
        setAttributeInternal(FOUNDERS, value);
    }

    /**
     * Gets the attribute value for MAIN_NUMBER using the alias name MainNumber.
     * @return the MAIN_NUMBER
     */
    public String getMainNumber() {
        return (String) getAttributeInternal(MAINNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for MAIN_NUMBER using the alias name MainNumber.
     * @param value value to set the MAIN_NUMBER
     */
    public void setMainNumber(String value) {
        setAttributeInternal(MAINNUMBER, value);
    }

    /**
     * Gets the attribute value for REG_DOC_NAME using the alias name RegDocName.
     * @return the REG_DOC_NAME
     */
    public String getRegDocName() {
        return (String) getAttributeInternal(REGDOCNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for REG_DOC_NAME using the alias name RegDocName.
     * @param value value to set the REG_DOC_NAME
     */
    public void setRegDocName(String value) {
        setAttributeInternal(REGDOCNAME, value);
    }

    /**
     * Gets the attribute value for END_REG_DOC_DATE using the alias name EndRegDocDate.
     * @return the END_REG_DOC_DATE
     */
    public Date getEndRegDocDate() {
        return (Date) getAttributeInternal(ENDREGDOCDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_REG_DOC_DATE using the alias name EndRegDocDate.
     * @param value value to set the END_REG_DOC_DATE
     */
    public void setEndRegDocDate(Date value) {
        setAttributeInternal(ENDREGDOCDATE, value);
    }

    /**
     * Gets the attribute value for REG_DOC_STATE using the alias name RegDocState.
     * @return the REG_DOC_STATE
     */
    public Number getRegDocState() {
        return (Number) getAttributeInternal(REGDOCSTATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REG_DOC_STATE using the alias name RegDocState.
     * @param value value to set the REG_DOC_STATE
     */
    public void setRegDocState(Number value) {
        setAttributeInternal(REGDOCSTATE, value);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for ARC_ID using the alias name ArcId.
     * @return the ARC_ID
     */
    public String getArcId() {
        return (String) getAttributeInternal(ARCID);
    }

    /**
     * Sets <code>value</code> as attribute value for ARC_ID using the alias name ArcId.
     * @param value value to set the ARC_ID
     */
    public void setArcId(String value) {
        setAttributeInternal(ARCID, value);
    }

    /**
     * Gets the attribute value for VIP using the alias name Vip.
     * @return the VIP
     */
    public Number getVip() {
        return (Number) getAttributeInternal(VIP);
    }

    /**
     * Sets <code>value</code> as attribute value for VIP using the alias name Vip.
     * @param value value to set the VIP
     */
    public void setVip(Number value) {
        setAttributeInternal(VIP, value);
    }

    /**
     * Gets the attribute value for HASH_VALUE using the alias name HashValue.
     * @return the HASH_VALUE
     */
    public Number getHashValue() {
        return (Number) getAttributeInternal(HASHVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for HASH_VALUE using the alias name HashValue.
     * @param value value to set the HASH_VALUE
     */
    public void setHashValue(Number value) {
        setAttributeInternal(HASHVALUE, value);
    }

    /**
     * Gets the attribute value for OLD_STATUS using the alias name OldStatus.
     * @return the OLD_STATUS
     */
    public Number getOldStatus() {
        return (Number) getAttributeInternal(OLDSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for OLD_STATUS using the alias name OldStatus.
     * @param value value to set the OLD_STATUS
     */
    public void setOldStatus(Number value) {
        setAttributeInternal(OLDSTATUS, value);
    }

    /**
     * Gets the attribute value for COMPARE_STATUS using the alias name CompareStatus.
     * @return the COMPARE_STATUS
     */
    public Number getCompareStatus() {
        return (Number) getAttributeInternal(COMPARESTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPARE_STATUS using the alias name CompareStatus.
     * @param value value to set the COMPARE_STATUS
     */
    public void setCompareStatus(Number value) {
        setAttributeInternal(COMPARESTATUS, value);
    }

    /**
     * Gets the attribute value for COMPARE_DATE using the alias name CompareDate.
     * @return the COMPARE_DATE
     */
    public Date getCompareDate() {
        return (Date) getAttributeInternal(COMPAREDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPARE_DATE using the alias name CompareDate.
     * @param value value to set the COMPARE_DATE
     */
    public void setCompareDate(Date value) {
        setAttributeInternal(COMPAREDATE, value);
    }

    /**
     * Gets the attribute value for E_MAIL using the alias name EMail.
     * @return the E_MAIL
     */
    public String getEMail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for E_MAIL using the alias name EMail.
     * @param value value to set the E_MAIL
     */
    public void setEMail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for NATIONALITY2 using the alias name Nationality2.
     * @return the NATIONALITY2
     */
    public String getNationality2() {
        return (String) getAttributeInternal(NATIONALITY2);
    }

    /**
     * Sets <code>value</code> as attribute value for NATIONALITY2 using the alias name Nationality2.
     * @param value value to set the NATIONALITY2
     */
    public void setNationality2(String value) {
        setAttributeInternal(NATIONALITY2, value);
    }

    /**
     * Gets the attribute value for PSG_CASE using the alias name PsgCase.
     * @return the PSG_CASE
     */
    public String getPsgCase() {
        return (String) getAttributeInternal(PSGCASE);
    }

    /**
     * Sets <code>value</code> as attribute value for PSG_CASE using the alias name PsgCase.
     * @param value value to set the PSG_CASE
     */
    public void setPsgCase(String value) {
        setAttributeInternal(PSGCASE, value);
    }

    /**
     * Gets the attribute value for ARC_COMMENTS using the alias name ArcComments.
     * @return the ARC_COMMENTS
     */
    public String getArcComments() {
        return (String) getAttributeInternal(ARCCOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for ARC_COMMENTS using the alias name ArcComments.
     * @param value value to set the ARC_COMMENTS
     */
    public void setArcComments(String value) {
        setAttributeInternal(ARCCOMMENTS, value);
    }

    /**
     * Gets the attribute value for PSG_TYPE using the alias name PsgType.
     * @return the PSG_TYPE
     */
    public String getPsgType() {
        return (String) getAttributeInternal(PSGTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for PSG_TYPE using the alias name PsgType.
     * @param value value to set the PSG_TYPE
     */
    public void setPsgType(String value) {
        setAttributeInternal(PSGTYPE, value);
    }

    /**
     * Gets the attribute value for IS_OWNER using the alias name IsOwner.
     * @return the IS_OWNER
     */
    public String getIsOwner() {
        return (String) getAttributeInternal(ISOWNER);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_OWNER using the alias name IsOwner.
     * @param value value to set the IS_OWNER
     */
    public void setIsOwner(String value) {
        setAttributeInternal(ISOWNER, value);
    }

    /**
     * Gets the attribute value for IS_GUARD using the alias name IsGuard.
     * @return the IS_GUARD
     */
    public String getIsGuard() {
        return (String) getAttributeInternal(ISGUARD);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_GUARD using the alias name IsGuard.
     * @param value value to set the IS_GUARD
     */
    public void setIsGuard(String value) {
        setAttributeInternal(ISGUARD, value);
    }

    /**
     * Gets the attribute value for IS_EMPLOYEE using the alias name IsEmployee.
     * @return the IS_EMPLOYEE
     */
    public String getIsEmployee() {
        return (String) getAttributeInternal(ISEMPLOYEE);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_EMPLOYEE using the alias name IsEmployee.
     * @param value value to set the IS_EMPLOYEE
     */
    public void setIsEmployee(String value) {
        setAttributeInternal(ISEMPLOYEE, value);
    }

    /**
     * Gets the attribute value for LRR_STATE using the alias name LrrState.
     * @return the LRR_STATE
     */
    public Number getLrrState() {
        return (Number) getAttributeInternal(LRRSTATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LRR_STATE using the alias name LrrState.
     * @param value value to set the LRR_STATE
     */
    public void setLrrState(Number value) {
        setAttributeInternal(LRRSTATE, value);
    }

    /**
     * Gets the attribute value for PHONE using the alias name Phone.
     * @return the PHONE
     */
    public String getPhone() {
        return (String) getAttributeInternal(PHONE);
    }

    /**
     * Sets <code>value</code> as attribute value for PHONE using the alias name Phone.
     * @param value value to set the PHONE
     */
    public void setPhone(String value) {
        setAttributeInternal(PHONE, value);
    }


    /**
     * Gets the attribute value for DELETE_ROW using the alias name DeleteRow.
     * @return the DELETE_ROW
     */
    public Boolean getDeleteRow() {
        return (Boolean) getAttributeInternal(DELETEROW);
    }

    /**
     * Sets <code>value</code> as attribute value for DELETE_ROW using the alias name DeleteRow.
     * @param value value to set the DELETE_ROW
     */
    public void setDeleteRow(Boolean value) {
        setAttributeInternal(DELETEROW, value);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EntPersonsView.
     */
    public RowIterator getEntPersonsView() {
        return (RowIterator)getAttributeInternal(ENTPERSONSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EntAddressesView.
     */
    public RowIterator getEntAddressesView() {
        return (RowIterator)getAttributeInternal(ENTADDRESSESVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DocRelationsView.
     */
    public RowIterator getDocRelationsView() {
        return (RowIterator)getAttributeInternal(DOCRELATIONSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link RPersonGunsView.
     */
    public RowIterator getRPersonGunsView() {
        return (RowIterator)getAttributeInternal(RPERSONGUNSVIEW);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EntPersonsRovdView.
     */
    public RowIterator getEntPersonsRovdView() {
        return (RowIterator)getAttributeInternal(ENTPERSONSROVDVIEW);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link EntPhotoView.
     */
    public Row getEntPhotoView() {
        return (Row)getAttributeInternal(ENTPHOTOVIEW);
    }

    /**
     * Sets the master-detail link EntPhotoView between this object and <code>value</code>.
     */
    public void setEntPhotoView(Row value) {
        setAttributeInternal(ENTPHOTOVIEW, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link VSuperDocView.
     */
    public RowIterator getVSuperDocView() {
        return (RowIterator)getAttributeInternal(VSUPERDOCVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountryView1.
     */
    public RowSet getCountryView1() {
        return (RowSet)getAttributeInternal(COUNTRYVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TypeDocView1.
     */
    public RowSet getTypeDocView1() {
        return (RowSet)getAttributeInternal(TYPEDOCVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TypePersonView1.
     */
    public RowSet getTypePersonView1() {
        return (RowSet)getAttributeInternal(TYPEPERSONVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> YesNo10_1.
     */
    public RowSet getYesNo10_1() {
        return (RowSet)getAttributeInternal(YESNO10_1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AcsUsersView2.
     */
    public RowSet getAcsUsersView2() {
        return (RowSet)getAttributeInternal(ACSUSERSVIEW2);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
    
}
