package ru.rdtex.mvd.weapon.model.vo;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 31 15:07:33 MSD 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RegionDeptViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RegionDeptViewImpl() {
    }


    /**
     * Returns the variable value for region_code.
     * @return variable value for region_code
     */
    public Number getregion_code() {
        return (Number)ensureVariableManager().getVariableValue("region_code");
    }

    /**
     * Sets <code>value</code> for variable region_code.
     * @param value value to bind as region_code
     */
    public void setregion_code(Number value) {
        ensureVariableManager().setVariableValue("region_code", value);
    }

    /**
     * Returns the variable value for ftitle.
     * @return variable value for ftitle
     */
    public String getftitle() {
        return (String)ensureVariableManager().getVariableValue("ftitle");
    }

    /**
     * Sets <code>value</code> for variable ftitle.
     * @param value value to bind as ftitle
     */
    public void setftitle(String value) {
        ensureVariableManager().setVariableValue("ftitle", value);
    }
}
