package ru.rdtex.mvd.weapon.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 11 14:25:14 MSD 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TypeLicenceViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TypeLicenceViewImpl() {
    }


    /**
     * Returns the variable value for typePerson.
     * @return variable value for typePerson
     */
    public String gettypePerson() {
        return (String)ensureVariableManager().getVariableValue("typePerson");
    }

    /**
     * Sets <code>value</code> for variable typePerson.
     * @param value value to bind as typePerson
     */
    public void settypePerson(String value) {
        ensureVariableManager().setVariableValue("typePerson", value);
    }

    /**
     * Returns the variable value for typeBlank.
     * @return variable value for typeBlank
     */
    public String gettypeBlank() {
        return (String)ensureVariableManager().getVariableValue("typeBlank");
    }

    /**
     * Sets <code>value</code> for variable typeBlank.
     * @param value value to bind as typeBlank
     */
    public void settypeBlank(String value) {
        ensureVariableManager().setVariableValue("typeBlank", value);
    }

    /**
     * Returns the variable value for id.
     * @return variable value for id
     */
    public String getid() {
        return (String)ensureVariableManager().getVariableValue("id");
    }

    /**
     * Sets <code>value</code> for variable id.
     * @param value value to bind as id
     */
    public void setid(String value) {
        ensureVariableManager().setVariableValue("id", value);
    }
}
