package ru.rdtex.mvd.weapon.model.vo.read.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 08 18:31:24 MSD 2012
// ---------------------------------------------------------------------
public interface VSuperDocView extends ViewObject {
    void deleteSelectedRows();
}
