package ru.rdtex.mvd.weapon.model.vo.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 17 13:13:56 MSD 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DocDocumentsRelationsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DocDocumentsRelationsViewImpl() {
    }

    /**
     * Returns the variable value for personId.
     * @return variable value for personId
     */
    public String getpersonId() {
        return (String)ensureVariableManager().getVariableValue("personId");
    }

    /**
     * Sets <code>value</code> for variable personId.
     * @param value value to bind as personId
     */
    public void setpersonId(String value) {
        ensureVariableManager().setVariableValue("personId", value);
    }
}
