package ru.rdtex.mvd.weapon.model.vo.lov;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 11 14:57:30 MSD 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TypeBlankRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ID {
            public Object get(TypeBlankRowImpl obj) {
                return obj.getID();
            }

            public void put(TypeBlankRowImpl obj, Object value) {
                obj.setID((String)value);
            }
        }
        ,
        NAME {
            public Object get(TypeBlankRowImpl obj) {
                return obj.getNAME();
            }

            public void put(TypeBlankRowImpl obj, Object value) {
                obj.setNAME((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(TypeBlankRowImpl object);

        public abstract void put(TypeBlankRowImpl object, Object value);

        public int index() {
            return TypeBlankRowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return TypeBlankRowImpl.AttributesEnum.firstIndex() + TypeBlankRowImpl.AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = TypeBlankRowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ID = AttributesEnum.ID.index();
    public static final int NAME = AttributesEnum.NAME.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TypeBlankRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ID.
     * @return the ID
     */
    public String getID() {
        return (String) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ID.
     * @param value value to set the  ID
     */
    public void setID(String value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NAME.
     * @return the NAME
     */
    public String getNAME() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NAME.
     * @param value value to set the  NAME
     */
    public void setNAME(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
