package ru.rdtex.mvd.weapon.model.vo.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 11 14:57:30 MSD 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TypeBlankImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TypeBlankImpl() {
    }
}
