// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package component.view;

import oracle.adfinternal.view.faces.taglib.region.RichDeclarativeComponentTag;
import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.bean.FacesBean;
import org.apache.myfaces.trinidad.bean.PropertyKey;
import javax.el.ValueExpression;
import javax.servlet.jsp.JspException;
import javax.el.MethodExpression;

public class CommandButtonDeleteDefTag extends RichDeclarativeComponentTag {

  public CommandButtonDeleteDefTag() {
  }

  protected String getViewId() {
    return "/commandButtonDeleteDef.jspx";
  }

  protected RichDeclarativeComponent createComponent() {
    return new CommandButtonDeleteDefComponent();
  }

  public void setText(ValueExpression text) {
    this._text = text;
  }

  public void setShortDesc(ValueExpression shortDesc) {
    this._shortDesc = shortDesc;
  }

  public void setIcon(ValueExpression icon) {
    this._icon = icon;
  }

  public void setDisabled(ValueExpression disabled) {
    this._disabled = disabled;
  }

  public void setAction(MethodExpression action) {
    this._action = action;
  }

  public void setActionListener(MethodExpression actionListener) {
    this._actionListener = actionListener;
  }


  protected void setProperties(FacesBean bean) {
    super.setProperties(bean);
    if (_text != null)
      bean.setValueExpression(_TEXT_KEY, _text);
    if (_shortDesc != null)
      bean.setValueExpression(_SHORTDESC_KEY, _shortDesc);
    if (_icon != null)
      bean.setValueExpression(_ICON_KEY, _icon);
    if (_disabled != null)
      bean.setValueExpression(_DISABLED_KEY, _disabled);
    if (_action != null)
      bean.setProperty(_ACTION_KEY, _action);
    if (_actionListener != null)
      bean.setProperty(_ACTIONLISTENER_KEY, _actionListener);
  }

  public void release() {
    super.release();
    _text = null;
    _shortDesc = null;
    _icon = null;
    _disabled = null;
    _action = null;
    _actionListener = null;
  }

  private ValueExpression _text;
  private ValueExpression _shortDesc;
  private ValueExpression _icon;
  private ValueExpression _disabled;
  private MethodExpression _action;
  private MethodExpression _actionListener;

  private static final PropertyKey _TEXT_KEY = PropertyKey.createPropertyKey("text");
  private static final PropertyKey _SHORTDESC_KEY = PropertyKey.createPropertyKey("shortDesc");
  private static final PropertyKey _ICON_KEY = PropertyKey.createPropertyKey("icon");
  private static final PropertyKey _DISABLED_KEY = PropertyKey.createPropertyKey("disabled");
  private static final PropertyKey _ACTION_KEY = PropertyKey.createPropertyKey("action");
  private static final PropertyKey _ACTIONLISTENER_KEY = PropertyKey.createPropertyKey("actionListener");

}
