package ru.rdtex.mvd.weapon.model.vo.client;

import oracle.jbo.client.remote.ViewUsageImpl;

import ru.rdtex.mvd.weapon.model.vo.common.EntPersonsView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 04 11:21:54 MSD 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EntPersonsViewClient extends ViewUsageImpl implements EntPersonsView {
    /**
     * This is the default constructor (do not remove).
     */
    public EntPersonsViewClient() {
    }

    public void deleteSelectedRows() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"deleteSelectedRows",null,null);
        return;
    }
}
