package ru.rdtex.mvd.weapon.model.vo.client;

import oracle.jbo.client.remote.ViewUsageImpl;

import ru.rdtex.mvd.weapon.model.vo.common.TypePersonView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 12 17:24:20 MSD 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TypePersonViewClient extends ViewUsageImpl implements TypePersonView {
    /**
     * This is the default constructor (do not remove).
     */
    public TypePersonViewClient() {
    }

    public void createRow(String Type) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"createRow",new String [] {"java.lang.String"},new Object[] {Type});
        return;
    }

    public void deleteSelectedRows(String Type) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"deleteSelectedRows",new String [] {"java.lang.String"},new Object[] {Type});
        return;
    }
}
