package ru.rdtex.mvd.weapon.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 12 17:24:20 MSD 2012
// ---------------------------------------------------------------------
public interface TypePersonView extends ViewObject {
    void createRow(String Type);

    void deleteSelectedRows(String Type);
}
