package ru.rdtex.mvd.weapon.model.vo.read;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 30 17:26:56 MSD 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class REntPersonsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public REntPersonsViewImpl() {
    }
}
