package ru.rdtex.mvd.weapon.model.vo.read;

import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 30 17:26:55 MSD 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class REntPersonsViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CountryCode {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getCountryCode();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setCountryCode((Number)value);
            }
        }
        ,
        TypedocCode {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getTypedocCode();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setTypedocCode((Number)value);
            }
        }
        ,
        PtypeCode {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getPtypeCode();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setPtypeCode((Number)value);
            }
        }
        ,
        ArcFio {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getArcFio();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setArcFio((String)value);
            }
        }
        ,
        Name {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getName();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setName((String)value);
            }
        }
        ,
        Otchestvo {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getOtchestvo();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setOtchestvo((String)value);
            }
        }
        ,
        JobTittle {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getJobTittle();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setJobTittle((String)value);
            }
        }
        ,
        BirthAdr {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getBirthAdr();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setBirthAdr((String)value);
            }
        }
        ,
        JobPost {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getJobPost();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setJobPost((String)value);
            }
        }
        ,
        JobPhone {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getJobPhone();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setJobPhone((String)value);
            }
        }
        ,
        EpId {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getEpId();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setEpId((Number)value);
            }
        }
        ,
        Id {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getId();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        Inn {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getInn();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setInn((String)value);
            }
        }
        ,
        DocSer {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getDocSer();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setDocSer((String)value);
            }
        }
        ,
        DocNum {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getDocNum();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setDocNum((String)value);
            }
        }
        ,
        DocDate {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getDocDate();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setDocDate((Date)value);
            }
        }
        ,
        DocOrg {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getDocOrg();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setDocOrg((String)value);
            }
        }
        ,
        UpdatedFlag {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getUpdatedFlag();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setUpdatedFlag((Number)value);
            }
        }
        ,
        Sex {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getSex();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setSex((String)value);
            }
        }
        ,
        Nationality {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getNationality();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setNationality((String)value);
            }
        }
        ,
        Birthday {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getBirthday();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setBirthday((Date)value);
            }
        }
        ,
        State {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getState();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setState((Number)value);
            }
        }
        ,
        Inserted {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getInserted();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setInserted((Date)value);
            }
        }
        ,
        InsertedBy {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getInsertedBy();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setInsertedBy((Number)value);
            }
        }
        ,
        TitleSurname {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getTitleSurname();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setTitleSurname((String)value);
            }
        }
        ,
        Updated {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getUpdated();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setUpdated((Date)value);
            }
        }
        ,
        UpdatedBy {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getUpdatedBy();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setUpdatedBy((Number)value);
            }
        }
        ,
        RegionCode {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getRegionCode();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setRegionCode((Number)value);
            }
        }
        ,
        OkrugCode {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getOkrugCode();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setOkrugCode((Number)value);
            }
        }
        ,
        DepTypeCode {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getDepTypeCode();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setDepTypeCode((Number)value);
            }
        }
        ,
        RegSertDate {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getRegSertDate();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setRegSertDate((Date)value);
            }
        }
        ,
        CharterDate {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getCharterDate();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setCharterDate((Date)value);
            }
        }
        ,
        TaxDate {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getTaxDate();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setTaxDate((Date)value);
            }
        }
        ,
        OtherDate {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getOtherDate();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setOtherDate((Date)value);
            }
        }
        ,
        EpType {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getEpType();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setEpType((String)value);
            }
        }
        ,
        ObjId {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getObjId();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setObjId((Number)value);
            }
        }
        ,
        ArcReason {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getArcReason();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setArcReason((String)value);
            }
        }
        ,
        ArcDate {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getArcDate();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setArcDate((Date)value);
            }
        }
        ,
        Wh {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getWh();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setWh((String)value);
            }
        }
        ,
        ArcIdDate {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getArcIdDate();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setArcIdDate((Date)value);
            }
        }
        ,
        SupervisCase {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getSupervisCase();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setSupervisCase((String)value);
            }
        }
        ,
        Founders {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getFounders();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setFounders((String)value);
            }
        }
        ,
        MainNumber {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getMainNumber();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setMainNumber((String)value);
            }
        }
        ,
        RegDocName {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getRegDocName();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setRegDocName((String)value);
            }
        }
        ,
        EndRegDocDate {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getEndRegDocDate();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setEndRegDocDate((Date)value);
            }
        }
        ,
        RegDocState {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getRegDocState();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setRegDocState((Number)value);
            }
        }
        ,
        Comments {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getComments();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setComments((String)value);
            }
        }
        ,
        ArcId {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getArcId();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setArcId((String)value);
            }
        }
        ,
        Vip {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getVip();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setVip((Number)value);
            }
        }
        ,
        HashValue {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getHashValue();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setHashValue((Number)value);
            }
        }
        ,
        OldStatus {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getOldStatus();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setOldStatus((Number)value);
            }
        }
        ,
        CompareStatus {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getCompareStatus();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setCompareStatus((Number)value);
            }
        }
        ,
        CompareDate {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getCompareDate();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setCompareDate((Date)value);
            }
        }
        ,
        EMail {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getEMail();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setEMail((String)value);
            }
        }
        ,
        Nationality2 {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getNationality2();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setNationality2((String)value);
            }
        }
        ,
        PsgCase {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getPsgCase();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setPsgCase((String)value);
            }
        }
        ,
        ArcComments {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getArcComments();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setArcComments((String)value);
            }
        }
        ,
        PsgType {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getPsgType();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setPsgType((String)value);
            }
        }
        ,
        IsOwner {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getIsOwner();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setIsOwner((String)value);
            }
        }
        ,
        IsGuard {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getIsGuard();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setIsGuard((String)value);
            }
        }
        ,
        IsEmployee {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getIsEmployee();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setIsEmployee((String)value);
            }
        }
        ,
        LrrState {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getLrrState();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setLrrState((Number)value);
            }
        }
        ,
        Phone {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getPhone();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setPhone((String)value);
            }
        }
        ,
        AddrPhone {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getAddrPhone();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setAddrPhone((String)value);
            }
        }
        ,
        AddrStrAdrs {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getAddrStrAdrs();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setAddrStrAdrs((String)value);
            }
        }
        ,
        AddrPolice {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getAddrPolice();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setAddrPolice((String)value);
            }
        }
        ,
        UserName {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getUserName();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setUserName((String)value);
            }
        }
        ,
        ChangeDate {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getChangeDate();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setChangeDate((Date)value);
            }
        }
        ,
        Photo {
            public Object get(REntPersonsViewRowImpl obj) {
                return obj.getPhoto();
            }

            public void put(REntPersonsViewRowImpl obj, Object value) {
                obj.setPhoto((BlobDomain)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(REntPersonsViewRowImpl object);

        public abstract void put(REntPersonsViewRowImpl object, Object value);

        public int index() {
            return REntPersonsViewRowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return REntPersonsViewRowImpl.AttributesEnum.firstIndex() + REntPersonsViewRowImpl.AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = REntPersonsViewRowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int COUNTRYCODE = AttributesEnum.CountryCode.index();
    public static final int TYPEDOCCODE = AttributesEnum.TypedocCode.index();
    public static final int PTYPECODE = AttributesEnum.PtypeCode.index();
    public static final int ARCFIO = AttributesEnum.ArcFio.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int OTCHESTVO = AttributesEnum.Otchestvo.index();
    public static final int JOBTITTLE = AttributesEnum.JobTittle.index();
    public static final int BIRTHADR = AttributesEnum.BirthAdr.index();
    public static final int JOBPOST = AttributesEnum.JobPost.index();
    public static final int JOBPHONE = AttributesEnum.JobPhone.index();
    public static final int EPID = AttributesEnum.EpId.index();
    public static final int ID = AttributesEnum.Id.index();
    public static final int INN = AttributesEnum.Inn.index();
    public static final int DOCSER = AttributesEnum.DocSer.index();
    public static final int DOCNUM = AttributesEnum.DocNum.index();
    public static final int DOCDATE = AttributesEnum.DocDate.index();
    public static final int DOCORG = AttributesEnum.DocOrg.index();
    public static final int UPDATEDFLAG = AttributesEnum.UpdatedFlag.index();
    public static final int SEX = AttributesEnum.Sex.index();
    public static final int NATIONALITY = AttributesEnum.Nationality.index();
    public static final int BIRTHDAY = AttributesEnum.Birthday.index();
    public static final int STATE = AttributesEnum.State.index();
    public static final int INSERTED = AttributesEnum.Inserted.index();
    public static final int INSERTEDBY = AttributesEnum.InsertedBy.index();
    public static final int TITLESURNAME = AttributesEnum.TitleSurname.index();
    public static final int UPDATED = AttributesEnum.Updated.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int REGIONCODE = AttributesEnum.RegionCode.index();
    public static final int OKRUGCODE = AttributesEnum.OkrugCode.index();
    public static final int DEPTYPECODE = AttributesEnum.DepTypeCode.index();
    public static final int REGSERTDATE = AttributesEnum.RegSertDate.index();
    public static final int CHARTERDATE = AttributesEnum.CharterDate.index();
    public static final int TAXDATE = AttributesEnum.TaxDate.index();
    public static final int OTHERDATE = AttributesEnum.OtherDate.index();
    public static final int EPTYPE = AttributesEnum.EpType.index();
    public static final int OBJID = AttributesEnum.ObjId.index();
    public static final int ARCREASON = AttributesEnum.ArcReason.index();
    public static final int ARCDATE = AttributesEnum.ArcDate.index();
    public static final int WH = AttributesEnum.Wh.index();
    public static final int ARCIDDATE = AttributesEnum.ArcIdDate.index();
    public static final int SUPERVISCASE = AttributesEnum.SupervisCase.index();
    public static final int FOUNDERS = AttributesEnum.Founders.index();
    public static final int MAINNUMBER = AttributesEnum.MainNumber.index();
    public static final int REGDOCNAME = AttributesEnum.RegDocName.index();
    public static final int ENDREGDOCDATE = AttributesEnum.EndRegDocDate.index();
    public static final int REGDOCSTATE = AttributesEnum.RegDocState.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int ARCID = AttributesEnum.ArcId.index();
    public static final int VIP = AttributesEnum.Vip.index();
    public static final int HASHVALUE = AttributesEnum.HashValue.index();
    public static final int OLDSTATUS = AttributesEnum.OldStatus.index();
    public static final int COMPARESTATUS = AttributesEnum.CompareStatus.index();
    public static final int COMPAREDATE = AttributesEnum.CompareDate.index();
    public static final int EMAIL = AttributesEnum.EMail.index();
    public static final int NATIONALITY2 = AttributesEnum.Nationality2.index();
    public static final int PSGCASE = AttributesEnum.PsgCase.index();
    public static final int ARCCOMMENTS = AttributesEnum.ArcComments.index();
    public static final int PSGTYPE = AttributesEnum.PsgType.index();
    public static final int ISOWNER = AttributesEnum.IsOwner.index();
    public static final int ISGUARD = AttributesEnum.IsGuard.index();
    public static final int ISEMPLOYEE = AttributesEnum.IsEmployee.index();
    public static final int LRRSTATE = AttributesEnum.LrrState.index();
    public static final int PHONE = AttributesEnum.Phone.index();
    public static final int ADDRPHONE = AttributesEnum.AddrPhone.index();
    public static final int ADDRSTRADRS = AttributesEnum.AddrStrAdrs.index();
    public static final int ADDRPOLICE = AttributesEnum.AddrPolice.index();
    public static final int USERNAME = AttributesEnum.UserName.index();
    public static final int CHANGEDATE = AttributesEnum.ChangeDate.index();
    public static final int PHOTO = AttributesEnum.Photo.index();

    /**
     * This is the default constructor (do not remove).
     */
    public REntPersonsViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute CountryCode.
     * @return the CountryCode
     */
    public Number getCountryCode() {
        return (Number) getAttributeInternal(COUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CountryCode.
     * @param value value to set the  CountryCode
     */
    public void setCountryCode(Number value) {
        setAttributeInternal(COUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TypedocCode.
     * @return the TypedocCode
     */
    public Number getTypedocCode() {
        return (Number) getAttributeInternal(TYPEDOCCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TypedocCode.
     * @param value value to set the  TypedocCode
     */
    public void setTypedocCode(Number value) {
        setAttributeInternal(TYPEDOCCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PtypeCode.
     * @return the PtypeCode
     */
    public Number getPtypeCode() {
        return (Number) getAttributeInternal(PTYPECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PtypeCode.
     * @param value value to set the  PtypeCode
     */
    public void setPtypeCode(Number value) {
        setAttributeInternal(PTYPECODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ArcFio.
     * @return the ArcFio
     */
    public String getArcFio() {
        return (String) getAttributeInternal(ARCFIO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ArcFio.
     * @param value value to set the  ArcFio
     */
    public void setArcFio(String value) {
        setAttributeInternal(ARCFIO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Name.
     * @return the Name
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Name.
     * @param value value to set the  Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Otchestvo.
     * @return the Otchestvo
     */
    public String getOtchestvo() {
        return (String) getAttributeInternal(OTCHESTVO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Otchestvo.
     * @param value value to set the  Otchestvo
     */
    public void setOtchestvo(String value) {
        setAttributeInternal(OTCHESTVO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute JobTittle.
     * @return the JobTittle
     */
    public String getJobTittle() {
        return (String) getAttributeInternal(JOBTITTLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute JobTittle.
     * @param value value to set the  JobTittle
     */
    public void setJobTittle(String value) {
        setAttributeInternal(JOBTITTLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BirthAdr.
     * @return the BirthAdr
     */
    public String getBirthAdr() {
        return (String) getAttributeInternal(BIRTHADR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BirthAdr.
     * @param value value to set the  BirthAdr
     */
    public void setBirthAdr(String value) {
        setAttributeInternal(BIRTHADR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute JobPost.
     * @return the JobPost
     */
    public String getJobPost() {
        return (String) getAttributeInternal(JOBPOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute JobPost.
     * @param value value to set the  JobPost
     */
    public void setJobPost(String value) {
        setAttributeInternal(JOBPOST, value);
    }

    /**
     * Gets the attribute value for the calculated attribute JobPhone.
     * @return the JobPhone
     */
    public String getJobPhone() {
        return (String) getAttributeInternal(JOBPHONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute JobPhone.
     * @param value value to set the  JobPhone
     */
    public void setJobPhone(String value) {
        setAttributeInternal(JOBPHONE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EpId.
     * @return the EpId
     */
    public Number getEpId() {
        return (Number) getAttributeInternal(EPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EpId.
     * @param value value to set the  EpId
     */
    public void setEpId(Number value) {
        setAttributeInternal(EPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Id.
     * @return the Id
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Id.
     * @param value value to set the  Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Inn.
     * @return the Inn
     */
    public String getInn() {
        return (String) getAttributeInternal(INN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Inn.
     * @param value value to set the  Inn
     */
    public void setInn(String value) {
        setAttributeInternal(INN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DocSer.
     * @return the DocSer
     */
    public String getDocSer() {
        return (String) getAttributeInternal(DOCSER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DocSer.
     * @param value value to set the  DocSer
     */
    public void setDocSer(String value) {
        setAttributeInternal(DOCSER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DocNum.
     * @return the DocNum
     */
    public String getDocNum() {
        return (String) getAttributeInternal(DOCNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DocNum.
     * @param value value to set the  DocNum
     */
    public void setDocNum(String value) {
        setAttributeInternal(DOCNUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DocDate.
     * @return the DocDate
     */
    public Date getDocDate() {
        return (Date) getAttributeInternal(DOCDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DocDate.
     * @param value value to set the  DocDate
     */
    public void setDocDate(Date value) {
        setAttributeInternal(DOCDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DocOrg.
     * @return the DocOrg
     */
    public String getDocOrg() {
        return (String) getAttributeInternal(DOCORG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DocOrg.
     * @param value value to set the  DocOrg
     */
    public void setDocOrg(String value) {
        setAttributeInternal(DOCORG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UpdatedFlag.
     * @return the UpdatedFlag
     */
    public Number getUpdatedFlag() {
        return (Number) getAttributeInternal(UPDATEDFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UpdatedFlag.
     * @param value value to set the  UpdatedFlag
     */
    public void setUpdatedFlag(Number value) {
        setAttributeInternal(UPDATEDFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Sex.
     * @return the Sex
     */
    public String getSex() {
        return (String) getAttributeInternal(SEX);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Sex.
     * @param value value to set the  Sex
     */
    public void setSex(String value) {
        setAttributeInternal(SEX, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Nationality.
     * @return the Nationality
     */
    public String getNationality() {
        return (String) getAttributeInternal(NATIONALITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Nationality.
     * @param value value to set the  Nationality
     */
    public void setNationality(String value) {
        setAttributeInternal(NATIONALITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Birthday.
     * @return the Birthday
     */
    public Date getBirthday() {
        return (Date) getAttributeInternal(BIRTHDAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Birthday.
     * @param value value to set the  Birthday
     */
    public void setBirthday(Date value) {
        setAttributeInternal(BIRTHDAY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute State.
     * @return the State
     */
    public Number getState() {
        return (Number) getAttributeInternal(STATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute State.
     * @param value value to set the  State
     */
    public void setState(Number value) {
        setAttributeInternal(STATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Inserted.
     * @return the Inserted
     */
    public Date getInserted() {
        return (Date) getAttributeInternal(INSERTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Inserted.
     * @param value value to set the  Inserted
     */
    public void setInserted(Date value) {
        setAttributeInternal(INSERTED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InsertedBy.
     * @return the InsertedBy
     */
    public Number getInsertedBy() {
        return (Number) getAttributeInternal(INSERTEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InsertedBy.
     * @param value value to set the  InsertedBy
     */
    public void setInsertedBy(Number value) {
        setAttributeInternal(INSERTEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TitleSurname.
     * @return the TitleSurname
     */
    public String getTitleSurname() {
        return (String) getAttributeInternal(TITLESURNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TitleSurname.
     * @param value value to set the  TitleSurname
     */
    public void setTitleSurname(String value) {
        setAttributeInternal(TITLESURNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Updated.
     * @return the Updated
     */
    public Date getUpdated() {
        return (Date) getAttributeInternal(UPDATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Updated.
     * @param value value to set the  Updated
     */
    public void setUpdated(Date value) {
        setAttributeInternal(UPDATED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UpdatedBy.
     * @return the UpdatedBy
     */
    public Number getUpdatedBy() {
        return (Number) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UpdatedBy.
     * @param value value to set the  UpdatedBy
     */
    public void setUpdatedBy(Number value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RegionCode.
     * @return the RegionCode
     */
    public Number getRegionCode() {
        return (Number) getAttributeInternal(REGIONCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RegionCode.
     * @param value value to set the  RegionCode
     */
    public void setRegionCode(Number value) {
        setAttributeInternal(REGIONCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OkrugCode.
     * @return the OkrugCode
     */
    public Number getOkrugCode() {
        return (Number) getAttributeInternal(OKRUGCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OkrugCode.
     * @param value value to set the  OkrugCode
     */
    public void setOkrugCode(Number value) {
        setAttributeInternal(OKRUGCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DepTypeCode.
     * @return the DepTypeCode
     */
    public Number getDepTypeCode() {
        return (Number) getAttributeInternal(DEPTYPECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DepTypeCode.
     * @param value value to set the  DepTypeCode
     */
    public void setDepTypeCode(Number value) {
        setAttributeInternal(DEPTYPECODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RegSertDate.
     * @return the RegSertDate
     */
    public Date getRegSertDate() {
        return (Date) getAttributeInternal(REGSERTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RegSertDate.
     * @param value value to set the  RegSertDate
     */
    public void setRegSertDate(Date value) {
        setAttributeInternal(REGSERTDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CharterDate.
     * @return the CharterDate
     */
    public Date getCharterDate() {
        return (Date) getAttributeInternal(CHARTERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CharterDate.
     * @param value value to set the  CharterDate
     */
    public void setCharterDate(Date value) {
        setAttributeInternal(CHARTERDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TaxDate.
     * @return the TaxDate
     */
    public Date getTaxDate() {
        return (Date) getAttributeInternal(TAXDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TaxDate.
     * @param value value to set the  TaxDate
     */
    public void setTaxDate(Date value) {
        setAttributeInternal(TAXDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OtherDate.
     * @return the OtherDate
     */
    public Date getOtherDate() {
        return (Date) getAttributeInternal(OTHERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OtherDate.
     * @param value value to set the  OtherDate
     */
    public void setOtherDate(Date value) {
        setAttributeInternal(OTHERDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EpType.
     * @return the EpType
     */
    public String getEpType() {
        return (String) getAttributeInternal(EPTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EpType.
     * @param value value to set the  EpType
     */
    public void setEpType(String value) {
        setAttributeInternal(EPTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjId.
     * @return the ObjId
     */
    public Number getObjId() {
        return (Number) getAttributeInternal(OBJID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ObjId.
     * @param value value to set the  ObjId
     */
    public void setObjId(Number value) {
        setAttributeInternal(OBJID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ArcReason.
     * @return the ArcReason
     */
    public String getArcReason() {
        return (String) getAttributeInternal(ARCREASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ArcReason.
     * @param value value to set the  ArcReason
     */
    public void setArcReason(String value) {
        setAttributeInternal(ARCREASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ArcDate.
     * @return the ArcDate
     */
    public Date getArcDate() {
        return (Date) getAttributeInternal(ARCDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ArcDate.
     * @param value value to set the  ArcDate
     */
    public void setArcDate(Date value) {
        setAttributeInternal(ARCDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Wh.
     * @return the Wh
     */
    public String getWh() {
        return (String) getAttributeInternal(WH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Wh.
     * @param value value to set the  Wh
     */
    public void setWh(String value) {
        setAttributeInternal(WH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ArcIdDate.
     * @return the ArcIdDate
     */
    public Date getArcIdDate() {
        return (Date) getAttributeInternal(ARCIDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ArcIdDate.
     * @param value value to set the  ArcIdDate
     */
    public void setArcIdDate(Date value) {
        setAttributeInternal(ARCIDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SupervisCase.
     * @return the SupervisCase
     */
    public String getSupervisCase() {
        return (String) getAttributeInternal(SUPERVISCASE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SupervisCase.
     * @param value value to set the  SupervisCase
     */
    public void setSupervisCase(String value) {
        setAttributeInternal(SUPERVISCASE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Founders.
     * @return the Founders
     */
    public String getFounders() {
        return (String) getAttributeInternal(FOUNDERS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Founders.
     * @param value value to set the  Founders
     */
    public void setFounders(String value) {
        setAttributeInternal(FOUNDERS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MainNumber.
     * @return the MainNumber
     */
    public String getMainNumber() {
        return (String) getAttributeInternal(MAINNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MainNumber.
     * @param value value to set the  MainNumber
     */
    public void setMainNumber(String value) {
        setAttributeInternal(MAINNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RegDocName.
     * @return the RegDocName
     */
    public String getRegDocName() {
        return (String) getAttributeInternal(REGDOCNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RegDocName.
     * @param value value to set the  RegDocName
     */
    public void setRegDocName(String value) {
        setAttributeInternal(REGDOCNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EndRegDocDate.
     * @return the EndRegDocDate
     */
    public Date getEndRegDocDate() {
        return (Date) getAttributeInternal(ENDREGDOCDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EndRegDocDate.
     * @param value value to set the  EndRegDocDate
     */
    public void setEndRegDocDate(Date value) {
        setAttributeInternal(ENDREGDOCDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RegDocState.
     * @return the RegDocState
     */
    public Number getRegDocState() {
        return (Number) getAttributeInternal(REGDOCSTATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RegDocState.
     * @param value value to set the  RegDocState
     */
    public void setRegDocState(Number value) {
        setAttributeInternal(REGDOCSTATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Comments.
     * @return the Comments
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Comments.
     * @param value value to set the  Comments
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ArcId.
     * @return the ArcId
     */
    public String getArcId() {
        return (String) getAttributeInternal(ARCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ArcId.
     * @param value value to set the  ArcId
     */
    public void setArcId(String value) {
        setAttributeInternal(ARCID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Vip.
     * @return the Vip
     */
    public Number getVip() {
        return (Number) getAttributeInternal(VIP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Vip.
     * @param value value to set the  Vip
     */
    public void setVip(Number value) {
        setAttributeInternal(VIP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute HashValue.
     * @return the HashValue
     */
    public Number getHashValue() {
        return (Number) getAttributeInternal(HASHVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HashValue.
     * @param value value to set the  HashValue
     */
    public void setHashValue(Number value) {
        setAttributeInternal(HASHVALUE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OldStatus.
     * @return the OldStatus
     */
    public Number getOldStatus() {
        return (Number) getAttributeInternal(OLDSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OldStatus.
     * @param value value to set the  OldStatus
     */
    public void setOldStatus(Number value) {
        setAttributeInternal(OLDSTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CompareStatus.
     * @return the CompareStatus
     */
    public Number getCompareStatus() {
        return (Number) getAttributeInternal(COMPARESTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CompareStatus.
     * @param value value to set the  CompareStatus
     */
    public void setCompareStatus(Number value) {
        setAttributeInternal(COMPARESTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CompareDate.
     * @return the CompareDate
     */
    public Date getCompareDate() {
        return (Date) getAttributeInternal(COMPAREDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CompareDate.
     * @param value value to set the  CompareDate
     */
    public void setCompareDate(Date value) {
        setAttributeInternal(COMPAREDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EMail.
     * @return the EMail
     */
    public String getEMail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EMail.
     * @param value value to set the  EMail
     */
    public void setEMail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Nationality2.
     * @return the Nationality2
     */
    public String getNationality2() {
        return (String) getAttributeInternal(NATIONALITY2);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Nationality2.
     * @param value value to set the  Nationality2
     */
    public void setNationality2(String value) {
        setAttributeInternal(NATIONALITY2, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PsgCase.
     * @return the PsgCase
     */
    public String getPsgCase() {
        return (String) getAttributeInternal(PSGCASE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PsgCase.
     * @param value value to set the  PsgCase
     */
    public void setPsgCase(String value) {
        setAttributeInternal(PSGCASE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ArcComments.
     * @return the ArcComments
     */
    public String getArcComments() {
        return (String) getAttributeInternal(ARCCOMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ArcComments.
     * @param value value to set the  ArcComments
     */
    public void setArcComments(String value) {
        setAttributeInternal(ARCCOMMENTS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PsgType.
     * @return the PsgType
     */
    public String getPsgType() {
        return (String) getAttributeInternal(PSGTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PsgType.
     * @param value value to set the  PsgType
     */
    public void setPsgType(String value) {
        setAttributeInternal(PSGTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsOwner.
     * @return the IsOwner
     */
    public String getIsOwner() {
        return (String) getAttributeInternal(ISOWNER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsOwner.
     * @param value value to set the  IsOwner
     */
    public void setIsOwner(String value) {
        setAttributeInternal(ISOWNER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsGuard.
     * @return the IsGuard
     */
    public String getIsGuard() {
        return (String) getAttributeInternal(ISGUARD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsGuard.
     * @param value value to set the  IsGuard
     */
    public void setIsGuard(String value) {
        setAttributeInternal(ISGUARD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsEmployee.
     * @return the IsEmployee
     */
    public String getIsEmployee() {
        return (String) getAttributeInternal(ISEMPLOYEE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsEmployee.
     * @param value value to set the  IsEmployee
     */
    public void setIsEmployee(String value) {
        setAttributeInternal(ISEMPLOYEE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LrrState.
     * @return the LrrState
     */
    public Number getLrrState() {
        return (Number) getAttributeInternal(LRRSTATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LrrState.
     * @param value value to set the  LrrState
     */
    public void setLrrState(Number value) {
        setAttributeInternal(LRRSTATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Phone.
     * @return the Phone
     */
    public String getPhone() {
        return (String) getAttributeInternal(PHONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Phone.
     * @param value value to set the  Phone
     */
    public void setPhone(String value) {
        setAttributeInternal(PHONE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AddrPhone.
     * @return the AddrPhone
     */
    public String getAddrPhone() {
        return (String) getAttributeInternal(ADDRPHONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AddrPhone.
     * @param value value to set the  AddrPhone
     */
    public void setAddrPhone(String value) {
        setAttributeInternal(ADDRPHONE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AddrStrAdrs.
     * @return the AddrStrAdrs
     */
    public String getAddrStrAdrs() {
        return (String) getAttributeInternal(ADDRSTRADRS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AddrStrAdrs.
     * @param value value to set the  AddrStrAdrs
     */
    public void setAddrStrAdrs(String value) {
        setAttributeInternal(ADDRSTRADRS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AddrPolice.
     * @return the AddrPolice
     */
    public String getAddrPolice() {
        return (String) getAttributeInternal(ADDRPOLICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AddrPolice.
     * @param value value to set the  AddrPolice
     */
    public void setAddrPolice(String value) {
        setAttributeInternal(ADDRPOLICE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UserName.
     * @return the UserName
     */
    public String getUserName() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UserName.
     * @param value value to set the  UserName
     */
    public void setUserName(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ChangeDate.
     * @return the ChangeDate
     */
    public Date getChangeDate() {
        return (Date) getAttributeInternal(CHANGEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ChangeDate.
     * @param value value to set the  ChangeDate
     */
    public void setChangeDate(Date value) {
        setAttributeInternal(CHANGEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Photo.
     * @return the Photo
     */
    public BlobDomain getPhoto() {
        return (BlobDomain) getAttributeInternal(PHOTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Photo.
     * @param value value to set the  Photo
     */
    public void setPhoto(BlobDomain value) {
        setAttributeInternal(PHOTO, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
