package ru.rdtex.mvd.weapon.model.vo.read;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 24 15:18:23 MSD 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RGunGunsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RGunGunsViewImpl() {
    }


    /**
     * Returns the bind variable value for personId.
     * @return bind variable value for personId
     */
    public String getpersonId() {
        return (String)getNamedWhereClauseParam("personId");
    }

    /**
     * Sets <code>value</code> for bind variable personId.
     * @param value value to bind as personId
     */
    public void setpersonId(String value) {
        setNamedWhereClauseParam("personId", value);
    }

    /**
     * Returns the bind variable value for isPerson.
     * @return bind variable value for isPerson
     */
    public String getisPerson() {
        return (String)getNamedWhereClauseParam("isPerson");
    }

    /**
     * Sets <code>value</code> for bind variable isPerson.
     * @param value value to bind as isPerson
     */
    public void setisPerson(String value) {
        setNamedWhereClauseParam("isPerson", value);
    }
}
